syntax = "proto3";
option java_package = "sjtu.opennet.textilepb";
option go_package = "pb";

//import "google/protobuf/any.proto";
//import "google/protobuf/timestamp.proto";
//import "model.proto";

message StreamBlockContent {
    string streamID = 1;
    uint64 index = 2;
    string data = 3; 
    bool isRoot = 4;
}

message StreamBlockContentList {
    repeated StreamBlockContent blocks = 1;    
}

message StreamRequest {
    string id = 1;
    uint64 streamMap = 2;
    uint64 startIndex = 3;
}
