// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stream_service.proto

package sjtu.opennet.textilepb;

public final class StreamService {
  private StreamService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface StreamBlockContentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:StreamBlockContent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string streamID = 1;</code>
     */
    java.lang.String getStreamID();
    /**
     * <code>string streamID = 1;</code>
     */
    com.google.protobuf.ByteString
        getStreamIDBytes();

    /**
     * <code>uint64 index = 2;</code>
     */
    long getIndex();

    /**
     * <code>string data = 3;</code>
     */
    java.lang.String getData();
    /**
     * <code>string data = 3;</code>
     */
    com.google.protobuf.ByteString
        getDataBytes();

    /**
     * <code>bool isRoot = 4;</code>
     */
    boolean getIsRoot();
  }
  /**
   * Protobuf type {@code StreamBlockContent}
   */
  public  static final class StreamBlockContent extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:StreamBlockContent)
      StreamBlockContentOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use StreamBlockContent.newBuilder() to construct.
    private StreamBlockContent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private StreamBlockContent() {
      streamID_ = "";
      index_ = 0L;
      data_ = "";
      isRoot_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private StreamBlockContent(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              streamID_ = s;
              break;
            }
            case 16: {

              index_ = input.readUInt64();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              data_ = s;
              break;
            }
            case 32: {

              isRoot_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sjtu.opennet.textilepb.StreamService.internal_static_StreamBlockContent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sjtu.opennet.textilepb.StreamService.internal_static_StreamBlockContent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sjtu.opennet.textilepb.StreamService.StreamBlockContent.class, sjtu.opennet.textilepb.StreamService.StreamBlockContent.Builder.class);
    }

    public static final int STREAMID_FIELD_NUMBER = 1;
    private volatile java.lang.Object streamID_;
    /**
     * <code>string streamID = 1;</code>
     */
    public java.lang.String getStreamID() {
      java.lang.Object ref = streamID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        streamID_ = s;
        return s;
      }
    }
    /**
     * <code>string streamID = 1;</code>
     */
    public com.google.protobuf.ByteString
        getStreamIDBytes() {
      java.lang.Object ref = streamID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        streamID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INDEX_FIELD_NUMBER = 2;
    private long index_;
    /**
     * <code>uint64 index = 2;</code>
     */
    public long getIndex() {
      return index_;
    }

    public static final int DATA_FIELD_NUMBER = 3;
    private volatile java.lang.Object data_;
    /**
     * <code>string data = 3;</code>
     */
    public java.lang.String getData() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        data_ = s;
        return s;
      }
    }
    /**
     * <code>string data = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDataBytes() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ISROOT_FIELD_NUMBER = 4;
    private boolean isRoot_;
    /**
     * <code>bool isRoot = 4;</code>
     */
    public boolean getIsRoot() {
      return isRoot_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getStreamIDBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, streamID_);
      }
      if (index_ != 0L) {
        output.writeUInt64(2, index_);
      }
      if (!getDataBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, data_);
      }
      if (isRoot_ != false) {
        output.writeBool(4, isRoot_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getStreamIDBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, streamID_);
      }
      if (index_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, index_);
      }
      if (!getDataBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, data_);
      }
      if (isRoot_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, isRoot_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof sjtu.opennet.textilepb.StreamService.StreamBlockContent)) {
        return super.equals(obj);
      }
      sjtu.opennet.textilepb.StreamService.StreamBlockContent other = (sjtu.opennet.textilepb.StreamService.StreamBlockContent) obj;

      boolean result = true;
      result = result && getStreamID()
          .equals(other.getStreamID());
      result = result && (getIndex()
          == other.getIndex());
      result = result && getData()
          .equals(other.getData());
      result = result && (getIsRoot()
          == other.getIsRoot());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STREAMID_FIELD_NUMBER;
      hash = (53 * hash) + getStreamID().hashCode();
      hash = (37 * hash) + INDEX_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getIndex());
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (37 * hash) + ISROOT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsRoot());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static sjtu.opennet.textilepb.StreamService.StreamBlockContent parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sjtu.opennet.textilepb.StreamService.StreamBlockContent parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sjtu.opennet.textilepb.StreamService.StreamBlockContent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sjtu.opennet.textilepb.StreamService.StreamBlockContent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sjtu.opennet.textilepb.StreamService.StreamBlockContent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sjtu.opennet.textilepb.StreamService.StreamBlockContent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sjtu.opennet.textilepb.StreamService.StreamBlockContent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sjtu.opennet.textilepb.StreamService.StreamBlockContent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static sjtu.opennet.textilepb.StreamService.StreamBlockContent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static sjtu.opennet.textilepb.StreamService.StreamBlockContent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static sjtu.opennet.textilepb.StreamService.StreamBlockContent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sjtu.opennet.textilepb.StreamService.StreamBlockContent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(sjtu.opennet.textilepb.StreamService.StreamBlockContent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code StreamBlockContent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:StreamBlockContent)
        sjtu.opennet.textilepb.StreamService.StreamBlockContentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sjtu.opennet.textilepb.StreamService.internal_static_StreamBlockContent_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sjtu.opennet.textilepb.StreamService.internal_static_StreamBlockContent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                sjtu.opennet.textilepb.StreamService.StreamBlockContent.class, sjtu.opennet.textilepb.StreamService.StreamBlockContent.Builder.class);
      }

      // Construct using sjtu.opennet.textilepb.StreamService.StreamBlockContent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        streamID_ = "";

        index_ = 0L;

        data_ = "";

        isRoot_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sjtu.opennet.textilepb.StreamService.internal_static_StreamBlockContent_descriptor;
      }

      @java.lang.Override
      public sjtu.opennet.textilepb.StreamService.StreamBlockContent getDefaultInstanceForType() {
        return sjtu.opennet.textilepb.StreamService.StreamBlockContent.getDefaultInstance();
      }

      @java.lang.Override
      public sjtu.opennet.textilepb.StreamService.StreamBlockContent build() {
        sjtu.opennet.textilepb.StreamService.StreamBlockContent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public sjtu.opennet.textilepb.StreamService.StreamBlockContent buildPartial() {
        sjtu.opennet.textilepb.StreamService.StreamBlockContent result = new sjtu.opennet.textilepb.StreamService.StreamBlockContent(this);
        result.streamID_ = streamID_;
        result.index_ = index_;
        result.data_ = data_;
        result.isRoot_ = isRoot_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof sjtu.opennet.textilepb.StreamService.StreamBlockContent) {
          return mergeFrom((sjtu.opennet.textilepb.StreamService.StreamBlockContent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(sjtu.opennet.textilepb.StreamService.StreamBlockContent other) {
        if (other == sjtu.opennet.textilepb.StreamService.StreamBlockContent.getDefaultInstance()) return this;
        if (!other.getStreamID().isEmpty()) {
          streamID_ = other.streamID_;
          onChanged();
        }
        if (other.getIndex() != 0L) {
          setIndex(other.getIndex());
        }
        if (!other.getData().isEmpty()) {
          data_ = other.data_;
          onChanged();
        }
        if (other.getIsRoot() != false) {
          setIsRoot(other.getIsRoot());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        sjtu.opennet.textilepb.StreamService.StreamBlockContent parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (sjtu.opennet.textilepb.StreamService.StreamBlockContent) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object streamID_ = "";
      /**
       * <code>string streamID = 1;</code>
       */
      public java.lang.String getStreamID() {
        java.lang.Object ref = streamID_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          streamID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string streamID = 1;</code>
       */
      public com.google.protobuf.ByteString
          getStreamIDBytes() {
        java.lang.Object ref = streamID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          streamID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string streamID = 1;</code>
       */
      public Builder setStreamID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        streamID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string streamID = 1;</code>
       */
      public Builder clearStreamID() {
        
        streamID_ = getDefaultInstance().getStreamID();
        onChanged();
        return this;
      }
      /**
       * <code>string streamID = 1;</code>
       */
      public Builder setStreamIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        streamID_ = value;
        onChanged();
        return this;
      }

      private long index_ ;
      /**
       * <code>uint64 index = 2;</code>
       */
      public long getIndex() {
        return index_;
      }
      /**
       * <code>uint64 index = 2;</code>
       */
      public Builder setIndex(long value) {
        
        index_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 index = 2;</code>
       */
      public Builder clearIndex() {
        
        index_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object data_ = "";
      /**
       * <code>string data = 3;</code>
       */
      public java.lang.String getData() {
        java.lang.Object ref = data_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          data_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string data = 3;</code>
       */
      public com.google.protobuf.ByteString
          getDataBytes() {
        java.lang.Object ref = data_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          data_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string data = 3;</code>
       */
      public Builder setData(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string data = 3;</code>
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      /**
       * <code>string data = 3;</code>
       */
      public Builder setDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        data_ = value;
        onChanged();
        return this;
      }

      private boolean isRoot_ ;
      /**
       * <code>bool isRoot = 4;</code>
       */
      public boolean getIsRoot() {
        return isRoot_;
      }
      /**
       * <code>bool isRoot = 4;</code>
       */
      public Builder setIsRoot(boolean value) {
        
        isRoot_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool isRoot = 4;</code>
       */
      public Builder clearIsRoot() {
        
        isRoot_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:StreamBlockContent)
    }

    // @@protoc_insertion_point(class_scope:StreamBlockContent)
    private static final sjtu.opennet.textilepb.StreamService.StreamBlockContent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new sjtu.opennet.textilepb.StreamService.StreamBlockContent();
    }

    public static sjtu.opennet.textilepb.StreamService.StreamBlockContent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<StreamBlockContent>
        PARSER = new com.google.protobuf.AbstractParser<StreamBlockContent>() {
      @java.lang.Override
      public StreamBlockContent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new StreamBlockContent(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<StreamBlockContent> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<StreamBlockContent> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public sjtu.opennet.textilepb.StreamService.StreamBlockContent getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface StreamBlockContentListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:StreamBlockContentList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .StreamBlockContent blocks = 1;</code>
     */
    java.util.List<sjtu.opennet.textilepb.StreamService.StreamBlockContent> 
        getBlocksList();
    /**
     * <code>repeated .StreamBlockContent blocks = 1;</code>
     */
    sjtu.opennet.textilepb.StreamService.StreamBlockContent getBlocks(int index);
    /**
     * <code>repeated .StreamBlockContent blocks = 1;</code>
     */
    int getBlocksCount();
    /**
     * <code>repeated .StreamBlockContent blocks = 1;</code>
     */
    java.util.List<? extends sjtu.opennet.textilepb.StreamService.StreamBlockContentOrBuilder> 
        getBlocksOrBuilderList();
    /**
     * <code>repeated .StreamBlockContent blocks = 1;</code>
     */
    sjtu.opennet.textilepb.StreamService.StreamBlockContentOrBuilder getBlocksOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code StreamBlockContentList}
   */
  public  static final class StreamBlockContentList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:StreamBlockContentList)
      StreamBlockContentListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use StreamBlockContentList.newBuilder() to construct.
    private StreamBlockContentList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private StreamBlockContentList() {
      blocks_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private StreamBlockContentList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                blocks_ = new java.util.ArrayList<sjtu.opennet.textilepb.StreamService.StreamBlockContent>();
                mutable_bitField0_ |= 0x00000001;
              }
              blocks_.add(
                  input.readMessage(sjtu.opennet.textilepb.StreamService.StreamBlockContent.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          blocks_ = java.util.Collections.unmodifiableList(blocks_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sjtu.opennet.textilepb.StreamService.internal_static_StreamBlockContentList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sjtu.opennet.textilepb.StreamService.internal_static_StreamBlockContentList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sjtu.opennet.textilepb.StreamService.StreamBlockContentList.class, sjtu.opennet.textilepb.StreamService.StreamBlockContentList.Builder.class);
    }

    public static final int BLOCKS_FIELD_NUMBER = 1;
    private java.util.List<sjtu.opennet.textilepb.StreamService.StreamBlockContent> blocks_;
    /**
     * <code>repeated .StreamBlockContent blocks = 1;</code>
     */
    public java.util.List<sjtu.opennet.textilepb.StreamService.StreamBlockContent> getBlocksList() {
      return blocks_;
    }
    /**
     * <code>repeated .StreamBlockContent blocks = 1;</code>
     */
    public java.util.List<? extends sjtu.opennet.textilepb.StreamService.StreamBlockContentOrBuilder> 
        getBlocksOrBuilderList() {
      return blocks_;
    }
    /**
     * <code>repeated .StreamBlockContent blocks = 1;</code>
     */
    public int getBlocksCount() {
      return blocks_.size();
    }
    /**
     * <code>repeated .StreamBlockContent blocks = 1;</code>
     */
    public sjtu.opennet.textilepb.StreamService.StreamBlockContent getBlocks(int index) {
      return blocks_.get(index);
    }
    /**
     * <code>repeated .StreamBlockContent blocks = 1;</code>
     */
    public sjtu.opennet.textilepb.StreamService.StreamBlockContentOrBuilder getBlocksOrBuilder(
        int index) {
      return blocks_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < blocks_.size(); i++) {
        output.writeMessage(1, blocks_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < blocks_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, blocks_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof sjtu.opennet.textilepb.StreamService.StreamBlockContentList)) {
        return super.equals(obj);
      }
      sjtu.opennet.textilepb.StreamService.StreamBlockContentList other = (sjtu.opennet.textilepb.StreamService.StreamBlockContentList) obj;

      boolean result = true;
      result = result && getBlocksList()
          .equals(other.getBlocksList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getBlocksCount() > 0) {
        hash = (37 * hash) + BLOCKS_FIELD_NUMBER;
        hash = (53 * hash) + getBlocksList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static sjtu.opennet.textilepb.StreamService.StreamBlockContentList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sjtu.opennet.textilepb.StreamService.StreamBlockContentList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sjtu.opennet.textilepb.StreamService.StreamBlockContentList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sjtu.opennet.textilepb.StreamService.StreamBlockContentList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sjtu.opennet.textilepb.StreamService.StreamBlockContentList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sjtu.opennet.textilepb.StreamService.StreamBlockContentList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sjtu.opennet.textilepb.StreamService.StreamBlockContentList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sjtu.opennet.textilepb.StreamService.StreamBlockContentList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static sjtu.opennet.textilepb.StreamService.StreamBlockContentList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static sjtu.opennet.textilepb.StreamService.StreamBlockContentList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static sjtu.opennet.textilepb.StreamService.StreamBlockContentList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sjtu.opennet.textilepb.StreamService.StreamBlockContentList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(sjtu.opennet.textilepb.StreamService.StreamBlockContentList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code StreamBlockContentList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:StreamBlockContentList)
        sjtu.opennet.textilepb.StreamService.StreamBlockContentListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sjtu.opennet.textilepb.StreamService.internal_static_StreamBlockContentList_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sjtu.opennet.textilepb.StreamService.internal_static_StreamBlockContentList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                sjtu.opennet.textilepb.StreamService.StreamBlockContentList.class, sjtu.opennet.textilepb.StreamService.StreamBlockContentList.Builder.class);
      }

      // Construct using sjtu.opennet.textilepb.StreamService.StreamBlockContentList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getBlocksFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (blocksBuilder_ == null) {
          blocks_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          blocksBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sjtu.opennet.textilepb.StreamService.internal_static_StreamBlockContentList_descriptor;
      }

      @java.lang.Override
      public sjtu.opennet.textilepb.StreamService.StreamBlockContentList getDefaultInstanceForType() {
        return sjtu.opennet.textilepb.StreamService.StreamBlockContentList.getDefaultInstance();
      }

      @java.lang.Override
      public sjtu.opennet.textilepb.StreamService.StreamBlockContentList build() {
        sjtu.opennet.textilepb.StreamService.StreamBlockContentList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public sjtu.opennet.textilepb.StreamService.StreamBlockContentList buildPartial() {
        sjtu.opennet.textilepb.StreamService.StreamBlockContentList result = new sjtu.opennet.textilepb.StreamService.StreamBlockContentList(this);
        int from_bitField0_ = bitField0_;
        if (blocksBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            blocks_ = java.util.Collections.unmodifiableList(blocks_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.blocks_ = blocks_;
        } else {
          result.blocks_ = blocksBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof sjtu.opennet.textilepb.StreamService.StreamBlockContentList) {
          return mergeFrom((sjtu.opennet.textilepb.StreamService.StreamBlockContentList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(sjtu.opennet.textilepb.StreamService.StreamBlockContentList other) {
        if (other == sjtu.opennet.textilepb.StreamService.StreamBlockContentList.getDefaultInstance()) return this;
        if (blocksBuilder_ == null) {
          if (!other.blocks_.isEmpty()) {
            if (blocks_.isEmpty()) {
              blocks_ = other.blocks_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureBlocksIsMutable();
              blocks_.addAll(other.blocks_);
            }
            onChanged();
          }
        } else {
          if (!other.blocks_.isEmpty()) {
            if (blocksBuilder_.isEmpty()) {
              blocksBuilder_.dispose();
              blocksBuilder_ = null;
              blocks_ = other.blocks_;
              bitField0_ = (bitField0_ & ~0x00000001);
              blocksBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getBlocksFieldBuilder() : null;
            } else {
              blocksBuilder_.addAllMessages(other.blocks_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        sjtu.opennet.textilepb.StreamService.StreamBlockContentList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (sjtu.opennet.textilepb.StreamService.StreamBlockContentList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<sjtu.opennet.textilepb.StreamService.StreamBlockContent> blocks_ =
        java.util.Collections.emptyList();
      private void ensureBlocksIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          blocks_ = new java.util.ArrayList<sjtu.opennet.textilepb.StreamService.StreamBlockContent>(blocks_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          sjtu.opennet.textilepb.StreamService.StreamBlockContent, sjtu.opennet.textilepb.StreamService.StreamBlockContent.Builder, sjtu.opennet.textilepb.StreamService.StreamBlockContentOrBuilder> blocksBuilder_;

      /**
       * <code>repeated .StreamBlockContent blocks = 1;</code>
       */
      public java.util.List<sjtu.opennet.textilepb.StreamService.StreamBlockContent> getBlocksList() {
        if (blocksBuilder_ == null) {
          return java.util.Collections.unmodifiableList(blocks_);
        } else {
          return blocksBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .StreamBlockContent blocks = 1;</code>
       */
      public int getBlocksCount() {
        if (blocksBuilder_ == null) {
          return blocks_.size();
        } else {
          return blocksBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .StreamBlockContent blocks = 1;</code>
       */
      public sjtu.opennet.textilepb.StreamService.StreamBlockContent getBlocks(int index) {
        if (blocksBuilder_ == null) {
          return blocks_.get(index);
        } else {
          return blocksBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .StreamBlockContent blocks = 1;</code>
       */
      public Builder setBlocks(
          int index, sjtu.opennet.textilepb.StreamService.StreamBlockContent value) {
        if (blocksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBlocksIsMutable();
          blocks_.set(index, value);
          onChanged();
        } else {
          blocksBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .StreamBlockContent blocks = 1;</code>
       */
      public Builder setBlocks(
          int index, sjtu.opennet.textilepb.StreamService.StreamBlockContent.Builder builderForValue) {
        if (blocksBuilder_ == null) {
          ensureBlocksIsMutable();
          blocks_.set(index, builderForValue.build());
          onChanged();
        } else {
          blocksBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .StreamBlockContent blocks = 1;</code>
       */
      public Builder addBlocks(sjtu.opennet.textilepb.StreamService.StreamBlockContent value) {
        if (blocksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBlocksIsMutable();
          blocks_.add(value);
          onChanged();
        } else {
          blocksBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .StreamBlockContent blocks = 1;</code>
       */
      public Builder addBlocks(
          int index, sjtu.opennet.textilepb.StreamService.StreamBlockContent value) {
        if (blocksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBlocksIsMutable();
          blocks_.add(index, value);
          onChanged();
        } else {
          blocksBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .StreamBlockContent blocks = 1;</code>
       */
      public Builder addBlocks(
          sjtu.opennet.textilepb.StreamService.StreamBlockContent.Builder builderForValue) {
        if (blocksBuilder_ == null) {
          ensureBlocksIsMutable();
          blocks_.add(builderForValue.build());
          onChanged();
        } else {
          blocksBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .StreamBlockContent blocks = 1;</code>
       */
      public Builder addBlocks(
          int index, sjtu.opennet.textilepb.StreamService.StreamBlockContent.Builder builderForValue) {
        if (blocksBuilder_ == null) {
          ensureBlocksIsMutable();
          blocks_.add(index, builderForValue.build());
          onChanged();
        } else {
          blocksBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .StreamBlockContent blocks = 1;</code>
       */
      public Builder addAllBlocks(
          java.lang.Iterable<? extends sjtu.opennet.textilepb.StreamService.StreamBlockContent> values) {
        if (blocksBuilder_ == null) {
          ensureBlocksIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, blocks_);
          onChanged();
        } else {
          blocksBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .StreamBlockContent blocks = 1;</code>
       */
      public Builder clearBlocks() {
        if (blocksBuilder_ == null) {
          blocks_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          blocksBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .StreamBlockContent blocks = 1;</code>
       */
      public Builder removeBlocks(int index) {
        if (blocksBuilder_ == null) {
          ensureBlocksIsMutable();
          blocks_.remove(index);
          onChanged();
        } else {
          blocksBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .StreamBlockContent blocks = 1;</code>
       */
      public sjtu.opennet.textilepb.StreamService.StreamBlockContent.Builder getBlocksBuilder(
          int index) {
        return getBlocksFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .StreamBlockContent blocks = 1;</code>
       */
      public sjtu.opennet.textilepb.StreamService.StreamBlockContentOrBuilder getBlocksOrBuilder(
          int index) {
        if (blocksBuilder_ == null) {
          return blocks_.get(index);  } else {
          return blocksBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .StreamBlockContent blocks = 1;</code>
       */
      public java.util.List<? extends sjtu.opennet.textilepb.StreamService.StreamBlockContentOrBuilder> 
           getBlocksOrBuilderList() {
        if (blocksBuilder_ != null) {
          return blocksBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(blocks_);
        }
      }
      /**
       * <code>repeated .StreamBlockContent blocks = 1;</code>
       */
      public sjtu.opennet.textilepb.StreamService.StreamBlockContent.Builder addBlocksBuilder() {
        return getBlocksFieldBuilder().addBuilder(
            sjtu.opennet.textilepb.StreamService.StreamBlockContent.getDefaultInstance());
      }
      /**
       * <code>repeated .StreamBlockContent blocks = 1;</code>
       */
      public sjtu.opennet.textilepb.StreamService.StreamBlockContent.Builder addBlocksBuilder(
          int index) {
        return getBlocksFieldBuilder().addBuilder(
            index, sjtu.opennet.textilepb.StreamService.StreamBlockContent.getDefaultInstance());
      }
      /**
       * <code>repeated .StreamBlockContent blocks = 1;</code>
       */
      public java.util.List<sjtu.opennet.textilepb.StreamService.StreamBlockContent.Builder> 
           getBlocksBuilderList() {
        return getBlocksFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          sjtu.opennet.textilepb.StreamService.StreamBlockContent, sjtu.opennet.textilepb.StreamService.StreamBlockContent.Builder, sjtu.opennet.textilepb.StreamService.StreamBlockContentOrBuilder> 
          getBlocksFieldBuilder() {
        if (blocksBuilder_ == null) {
          blocksBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              sjtu.opennet.textilepb.StreamService.StreamBlockContent, sjtu.opennet.textilepb.StreamService.StreamBlockContent.Builder, sjtu.opennet.textilepb.StreamService.StreamBlockContentOrBuilder>(
                  blocks_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          blocks_ = null;
        }
        return blocksBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:StreamBlockContentList)
    }

    // @@protoc_insertion_point(class_scope:StreamBlockContentList)
    private static final sjtu.opennet.textilepb.StreamService.StreamBlockContentList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new sjtu.opennet.textilepb.StreamService.StreamBlockContentList();
    }

    public static sjtu.opennet.textilepb.StreamService.StreamBlockContentList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<StreamBlockContentList>
        PARSER = new com.google.protobuf.AbstractParser<StreamBlockContentList>() {
      @java.lang.Override
      public StreamBlockContentList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new StreamBlockContentList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<StreamBlockContentList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<StreamBlockContentList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public sjtu.opennet.textilepb.StreamService.StreamBlockContentList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface StreamRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:StreamRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>uint64 streamMap = 2;</code>
     */
    long getStreamMap();

    /**
     * <code>uint64 startIndex = 3;</code>
     */
    long getStartIndex();
  }
  /**
   * Protobuf type {@code StreamRequest}
   */
  public  static final class StreamRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:StreamRequest)
      StreamRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use StreamRequest.newBuilder() to construct.
    private StreamRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private StreamRequest() {
      id_ = "";
      streamMap_ = 0L;
      startIndex_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private StreamRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 16: {

              streamMap_ = input.readUInt64();
              break;
            }
            case 24: {

              startIndex_ = input.readUInt64();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sjtu.opennet.textilepb.StreamService.internal_static_StreamRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sjtu.opennet.textilepb.StreamService.internal_static_StreamRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sjtu.opennet.textilepb.StreamService.StreamRequest.class, sjtu.opennet.textilepb.StreamService.StreamRequest.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STREAMMAP_FIELD_NUMBER = 2;
    private long streamMap_;
    /**
     * <code>uint64 streamMap = 2;</code>
     */
    public long getStreamMap() {
      return streamMap_;
    }

    public static final int STARTINDEX_FIELD_NUMBER = 3;
    private long startIndex_;
    /**
     * <code>uint64 startIndex = 3;</code>
     */
    public long getStartIndex() {
      return startIndex_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (streamMap_ != 0L) {
        output.writeUInt64(2, streamMap_);
      }
      if (startIndex_ != 0L) {
        output.writeUInt64(3, startIndex_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (streamMap_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, streamMap_);
      }
      if (startIndex_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, startIndex_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof sjtu.opennet.textilepb.StreamService.StreamRequest)) {
        return super.equals(obj);
      }
      sjtu.opennet.textilepb.StreamService.StreamRequest other = (sjtu.opennet.textilepb.StreamService.StreamRequest) obj;

      boolean result = true;
      result = result && getId()
          .equals(other.getId());
      result = result && (getStreamMap()
          == other.getStreamMap());
      result = result && (getStartIndex()
          == other.getStartIndex());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + STREAMMAP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getStreamMap());
      hash = (37 * hash) + STARTINDEX_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getStartIndex());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static sjtu.opennet.textilepb.StreamService.StreamRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sjtu.opennet.textilepb.StreamService.StreamRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sjtu.opennet.textilepb.StreamService.StreamRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sjtu.opennet.textilepb.StreamService.StreamRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sjtu.opennet.textilepb.StreamService.StreamRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sjtu.opennet.textilepb.StreamService.StreamRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sjtu.opennet.textilepb.StreamService.StreamRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sjtu.opennet.textilepb.StreamService.StreamRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static sjtu.opennet.textilepb.StreamService.StreamRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static sjtu.opennet.textilepb.StreamService.StreamRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static sjtu.opennet.textilepb.StreamService.StreamRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sjtu.opennet.textilepb.StreamService.StreamRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(sjtu.opennet.textilepb.StreamService.StreamRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code StreamRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:StreamRequest)
        sjtu.opennet.textilepb.StreamService.StreamRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sjtu.opennet.textilepb.StreamService.internal_static_StreamRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sjtu.opennet.textilepb.StreamService.internal_static_StreamRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                sjtu.opennet.textilepb.StreamService.StreamRequest.class, sjtu.opennet.textilepb.StreamService.StreamRequest.Builder.class);
      }

      // Construct using sjtu.opennet.textilepb.StreamService.StreamRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = "";

        streamMap_ = 0L;

        startIndex_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sjtu.opennet.textilepb.StreamService.internal_static_StreamRequest_descriptor;
      }

      @java.lang.Override
      public sjtu.opennet.textilepb.StreamService.StreamRequest getDefaultInstanceForType() {
        return sjtu.opennet.textilepb.StreamService.StreamRequest.getDefaultInstance();
      }

      @java.lang.Override
      public sjtu.opennet.textilepb.StreamService.StreamRequest build() {
        sjtu.opennet.textilepb.StreamService.StreamRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public sjtu.opennet.textilepb.StreamService.StreamRequest buildPartial() {
        sjtu.opennet.textilepb.StreamService.StreamRequest result = new sjtu.opennet.textilepb.StreamService.StreamRequest(this);
        result.id_ = id_;
        result.streamMap_ = streamMap_;
        result.startIndex_ = startIndex_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof sjtu.opennet.textilepb.StreamService.StreamRequest) {
          return mergeFrom((sjtu.opennet.textilepb.StreamService.StreamRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(sjtu.opennet.textilepb.StreamService.StreamRequest other) {
        if (other == sjtu.opennet.textilepb.StreamService.StreamRequest.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (other.getStreamMap() != 0L) {
          setStreamMap(other.getStreamMap());
        }
        if (other.getStartIndex() != 0L) {
          setStartIndex(other.getStartIndex());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        sjtu.opennet.textilepb.StreamService.StreamRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (sjtu.opennet.textilepb.StreamService.StreamRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private long streamMap_ ;
      /**
       * <code>uint64 streamMap = 2;</code>
       */
      public long getStreamMap() {
        return streamMap_;
      }
      /**
       * <code>uint64 streamMap = 2;</code>
       */
      public Builder setStreamMap(long value) {
        
        streamMap_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 streamMap = 2;</code>
       */
      public Builder clearStreamMap() {
        
        streamMap_ = 0L;
        onChanged();
        return this;
      }

      private long startIndex_ ;
      /**
       * <code>uint64 startIndex = 3;</code>
       */
      public long getStartIndex() {
        return startIndex_;
      }
      /**
       * <code>uint64 startIndex = 3;</code>
       */
      public Builder setStartIndex(long value) {
        
        startIndex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 startIndex = 3;</code>
       */
      public Builder clearStartIndex() {
        
        startIndex_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:StreamRequest)
    }

    // @@protoc_insertion_point(class_scope:StreamRequest)
    private static final sjtu.opennet.textilepb.StreamService.StreamRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new sjtu.opennet.textilepb.StreamService.StreamRequest();
    }

    public static sjtu.opennet.textilepb.StreamService.StreamRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<StreamRequest>
        PARSER = new com.google.protobuf.AbstractParser<StreamRequest>() {
      @java.lang.Override
      public StreamRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new StreamRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<StreamRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<StreamRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public sjtu.opennet.textilepb.StreamService.StreamRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StreamBlockContent_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StreamBlockContent_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StreamBlockContentList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StreamBlockContentList_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StreamRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StreamRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024stream_service.proto\"S\n\022StreamBlockCon" +
      "tent\022\020\n\010streamID\030\001 \001(\t\022\r\n\005index\030\002 \001(\004\022\014\n" +
      "\004data\030\003 \001(\t\022\016\n\006isRoot\030\004 \001(\010\"=\n\026StreamBlo" +
      "ckContentList\022#\n\006blocks\030\001 \003(\0132\023.StreamBl" +
      "ockContent\"B\n\rStreamRequest\022\n\n\002id\030\001 \001(\t\022" +
      "\021\n\tstreamMap\030\002 \001(\004\022\022\n\nstartIndex\030\003 \001(\004B\034" +
      "\n\026sjtu.opennet.textilepbZ\002pbb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_StreamBlockContent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_StreamBlockContent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StreamBlockContent_descriptor,
        new java.lang.String[] { "StreamID", "Index", "Data", "IsRoot", });
    internal_static_StreamBlockContentList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_StreamBlockContentList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StreamBlockContentList_descriptor,
        new java.lang.String[] { "Blocks", });
    internal_static_StreamRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_StreamRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StreamRequest_descriptor,
        new java.lang.String[] { "Id", "StreamMap", "StartIndex", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
