package stream

// Define all log tags.
// It was used by SJTU-OpenNetwotk/go-logparser

const (
	TAG_WORKERSTART = "WORKERSTART"
	TAG_WORKEREND = "WORKEREND"
	TAG_BLOCKSEND = "BLOCKSEND"
	TAG_BLOCKRECEIVE = "BLOCKRECV"
	TAG_STREAMREQUEST = "STREAMREQUEST"
	TAG_STREAMRESPONSE = "STREAMRESPONSE"
)
