package stream

// Define all log tags.
// It was used by SJTU-OpenNetwotk/go-logparser

const (
	TAG_STREAMSTART = "STREAM_START"
	TAG_STREAMEND = "STREAM_END"
	TAG_STREAMSUBSCRIBE = "STREAM_SUBSCRIBE"
	TAG_STREAMSEARCH = "STREAM_SEARCH"
	TAG_STREAM_COMPLETE = "STREAM_COMPLETE"
	TAG_WORKERSTART = "WORKER_START"
	TAG_WORKEREND = "WORKER_END"
	TAG_BLOCKSEND = "STREAM_BLOCK_SEND"
	TAG_BLOCKSEND_FAILED = "STREAM_BLOCK_SEND_FAILED"
	TAG_BLOCKSEND_COMPLETE = "STREAM_BLOCK_SEND_COMPLETE"
	TAG_BLOCKRECEIVE = "STREAM_BLOCK_RECV"
	TAG_STREAMREQUEST = "STREAM_REQUEST"
	TAG_STREAMRESPONSE = "STREAM_RESPONSE"
	TAG_STREAMREQUESTACCEPT = "STREAM_REQUEST_ACCEPT"
	TAG_STREAM_REQUEST_ACCEPTED = "STREAM_REQUEST_ACCEPTED"
	TAG_STREAMREQUESTREJECT = "STREAM_REQUEST_REJECT"
	TAG_WORKERSTORE_REMOVE = "WORKER_REMOVE"
	TAG_STREAM_SEARCHTIMEOUT = "STREAM_SEARCH_TIMEOUT"
	TAG_PROVIDER_ADD = "PROVIDER_ADD"
	TAG_PROVIDER_REMOVE = "PROVIDER_REMOVE"
	TAG_RETRY_SUBSCRIBE = "RETRY_SUBSCRIBE"
	TAG_SEARCH_BUSY = "SEARCH_BUSY"
	TAG_SEARCH_NOMETA = "SEARCH_NOMETA"
	TAG_SEARCH_NOPROVIDER = "SEARCH_NOPROVIDER"
	TAG_SEARCH_GETPROVIDER = "SEARCH_GETPROVIDER"
	TAG_WORKERSTORE_ADD = "WORKER_ADD"
	TAG_SERVICE_NEWMESSAGE = "SERVICE_NEW_MESSAGE"
	TAG_SERVICE_DONEMESSAGE = "SERVICE_DONE_MESSAGE"
	TAG_STREAM_STARTHANDLE = "STREAM_START_HANDLE"
	TAG_STREAM_DONEHANDLE = "STREAM_DONE_HANDLE"
	TAG_STATUS = "STREAM_STATUS"
)
