package stream

// Define all log tags.
// It was used by SJTU-OpenNetwotk/go-logparser

const (
	TAG_STREAMSTART = "STREAM_START"
	TAG_STREAMEND = "STREAM_END"
	TAG_WORKERSTART = "WORKER_START"
	TAG_WORKEREND = "WORKER_END"
	TAG_BLOCKSEND = "STREAM_BLOCK_SEND"
	TAG_BLOCKRECEIVE = "STREAM_BLOCK_RECV"
	TAG_STREAMREQUEST = "STREAM_REQUEST"
	TAG_STREAMUNSUBSCRIBE = "STREAM_UNSUBSCRIBE"
	TAG_STREAMRESPONSE = "STREAM_RESPONSE"
	TAG_STREAMREQUESTACCEPT = "STREAM_REQUEST_ACCEPT"
	TAG_STREAMREQUESTREJECT = "STREAM_REQUEST_REJECT"
	TAG_WORKERSTORE_REMOVE = "WORKER_REMOVE"
	TAG_WORKERSTORE_ADD = "WORKER_ADD"
)
