// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: cafe_service.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type CafeChallenge struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *CafeChallenge) Reset() {
	*x = CafeChallenge{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cafe_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CafeChallenge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CafeChallenge) ProtoMessage() {}

func (x *CafeChallenge) ProtoReflect() protoreflect.Message {
	mi := &file_cafe_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CafeChallenge.ProtoReflect.Descriptor instead.
func (*CafeChallenge) Descriptor() ([]byte, []int) {
	return file_cafe_service_proto_rawDescGZIP(), []int{0}
}

func (x *CafeChallenge) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type CafeNonce struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *CafeNonce) Reset() {
	*x = CafeNonce{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cafe_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CafeNonce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CafeNonce) ProtoMessage() {}

func (x *CafeNonce) ProtoReflect() protoreflect.Message {
	mi := &file_cafe_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CafeNonce.ProtoReflect.Descriptor instead.
func (*CafeNonce) Descriptor() ([]byte, []int) {
	return file_cafe_service_proto_rawDescGZIP(), []int{1}
}

func (x *CafeNonce) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type CafeRegistration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Value   string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Nonce   string `protobuf:"bytes,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Sig     []byte `protobuf:"bytes,4,opt,name=sig,proto3" json:"sig,omitempty"`
	Token   string `protobuf:"bytes,5,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *CafeRegistration) Reset() {
	*x = CafeRegistration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cafe_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CafeRegistration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CafeRegistration) ProtoMessage() {}

func (x *CafeRegistration) ProtoReflect() protoreflect.Message {
	mi := &file_cafe_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CafeRegistration.ProtoReflect.Descriptor instead.
func (*CafeRegistration) Descriptor() ([]byte, []int) {
	return file_cafe_service_proto_rawDescGZIP(), []int{2}
}

func (x *CafeRegistration) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CafeRegistration) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *CafeRegistration) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *CafeRegistration) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

func (x *CafeRegistration) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type CafeDeregistration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *CafeDeregistration) Reset() {
	*x = CafeDeregistration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cafe_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CafeDeregistration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CafeDeregistration) ProtoMessage() {}

func (x *CafeDeregistration) ProtoReflect() protoreflect.Message {
	mi := &file_cafe_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CafeDeregistration.ProtoReflect.Descriptor instead.
func (*CafeDeregistration) Descriptor() ([]byte, []int) {
	return file_cafe_service_proto_rawDescGZIP(), []int{3}
}

func (x *CafeDeregistration) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type CafeDeregistrationAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CafeDeregistrationAck) Reset() {
	*x = CafeDeregistrationAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cafe_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CafeDeregistrationAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CafeDeregistrationAck) ProtoMessage() {}

func (x *CafeDeregistrationAck) ProtoReflect() protoreflect.Message {
	mi := &file_cafe_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CafeDeregistrationAck.ProtoReflect.Descriptor instead.
func (*CafeDeregistrationAck) Descriptor() ([]byte, []int) {
	return file_cafe_service_proto_rawDescGZIP(), []int{4}
}

func (x *CafeDeregistrationAck) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CafeRefreshSession struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Access  string `protobuf:"bytes,1,opt,name=access,proto3" json:"access,omitempty"`
	Refresh string `protobuf:"bytes,2,opt,name=refresh,proto3" json:"refresh,omitempty"`
}

func (x *CafeRefreshSession) Reset() {
	*x = CafeRefreshSession{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cafe_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CafeRefreshSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CafeRefreshSession) ProtoMessage() {}

func (x *CafeRefreshSession) ProtoReflect() protoreflect.Message {
	mi := &file_cafe_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CafeRefreshSession.ProtoReflect.Descriptor instead.
func (*CafeRefreshSession) Descriptor() ([]byte, []int) {
	return file_cafe_service_proto_rawDescGZIP(), []int{5}
}

func (x *CafeRefreshSession) GetAccess() string {
	if x != nil {
		return x.Access
	}
	return ""
}

func (x *CafeRefreshSession) GetRefresh() string {
	if x != nil {
		return x.Refresh
	}
	return ""
}

type CafePublishPeer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Peer  *Peer  `protobuf:"bytes,2,opt,name=peer,proto3" json:"peer,omitempty"`
}

func (x *CafePublishPeer) Reset() {
	*x = CafePublishPeer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cafe_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CafePublishPeer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CafePublishPeer) ProtoMessage() {}

func (x *CafePublishPeer) ProtoReflect() protoreflect.Message {
	mi := &file_cafe_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CafePublishPeer.ProtoReflect.Descriptor instead.
func (*CafePublishPeer) Descriptor() ([]byte, []int) {
	return file_cafe_service_proto_rawDescGZIP(), []int{6}
}

func (x *CafePublishPeer) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CafePublishPeer) GetPeer() *Peer {
	if x != nil {
		return x.Peer
	}
	return nil
}

type CafePublishPeerAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CafePublishPeerAck) Reset() {
	*x = CafePublishPeerAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cafe_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CafePublishPeerAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CafePublishPeerAck) ProtoMessage() {}

func (x *CafePublishPeerAck) ProtoReflect() protoreflect.Message {
	mi := &file_cafe_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CafePublishPeerAck.ProtoReflect.Descriptor instead.
func (*CafePublishPeerAck) Descriptor() ([]byte, []int) {
	return file_cafe_service_proto_rawDescGZIP(), []int{7}
}

func (x *CafePublishPeerAck) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CafeStore struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Cids  []string `protobuf:"bytes,2,rep,name=cids,proto3" json:"cids,omitempty"`
}

func (x *CafeStore) Reset() {
	*x = CafeStore{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cafe_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CafeStore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CafeStore) ProtoMessage() {}

func (x *CafeStore) ProtoReflect() protoreflect.Message {
	mi := &file_cafe_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CafeStore.ProtoReflect.Descriptor instead.
func (*CafeStore) Descriptor() ([]byte, []int) {
	return file_cafe_service_proto_rawDescGZIP(), []int{8}
}

func (x *CafeStore) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CafeStore) GetCids() []string {
	if x != nil {
		return x.Cids
	}
	return nil
}

type CafeStoreAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CafeStoreAck) Reset() {
	*x = CafeStoreAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cafe_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CafeStoreAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CafeStoreAck) ProtoMessage() {}

func (x *CafeStoreAck) ProtoReflect() protoreflect.Message {
	mi := &file_cafe_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CafeStoreAck.ProtoReflect.Descriptor instead.
func (*CafeStoreAck) Descriptor() ([]byte, []int) {
	return file_cafe_service_proto_rawDescGZIP(), []int{9}
}

func (x *CafeStoreAck) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CafeUnstore struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Cids  []string `protobuf:"bytes,2,rep,name=cids,proto3" json:"cids,omitempty"`
}

func (x *CafeUnstore) Reset() {
	*x = CafeUnstore{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cafe_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CafeUnstore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CafeUnstore) ProtoMessage() {}

func (x *CafeUnstore) ProtoReflect() protoreflect.Message {
	mi := &file_cafe_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CafeUnstore.ProtoReflect.Descriptor instead.
func (*CafeUnstore) Descriptor() ([]byte, []int) {
	return file_cafe_service_proto_rawDescGZIP(), []int{10}
}

func (x *CafeUnstore) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CafeUnstore) GetCids() []string {
	if x != nil {
		return x.Cids
	}
	return nil
}

type CafeUnstoreAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cids []string `protobuf:"bytes,1,rep,name=cids,proto3" json:"cids,omitempty"`
}

func (x *CafeUnstoreAck) Reset() {
	*x = CafeUnstoreAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cafe_service_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CafeUnstoreAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CafeUnstoreAck) ProtoMessage() {}

func (x *CafeUnstoreAck) ProtoReflect() protoreflect.Message {
	mi := &file_cafe_service_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CafeUnstoreAck.ProtoReflect.Descriptor instead.
func (*CafeUnstoreAck) Descriptor() ([]byte, []int) {
	return file_cafe_service_proto_rawDescGZIP(), []int{11}
}

func (x *CafeUnstoreAck) GetCids() []string {
	if x != nil {
		return x.Cids
	}
	return nil
}

type CafeObjectList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cids []string `protobuf:"bytes,1,rep,name=cids,proto3" json:"cids,omitempty"`
}

func (x *CafeObjectList) Reset() {
	*x = CafeObjectList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cafe_service_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CafeObjectList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CafeObjectList) ProtoMessage() {}

func (x *CafeObjectList) ProtoReflect() protoreflect.Message {
	mi := &file_cafe_service_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CafeObjectList.ProtoReflect.Descriptor instead.
func (*CafeObjectList) Descriptor() ([]byte, []int) {
	return file_cafe_service_proto_rawDescGZIP(), []int{12}
}

func (x *CafeObjectList) GetCids() []string {
	if x != nil {
		return x.Cids
	}
	return nil
}

type CafeObject struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Cid   string `protobuf:"bytes,2,opt,name=cid,proto3" json:"cid,omitempty"`
	Data  []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Node  []byte `protobuf:"bytes,4,opt,name=node,proto3" json:"node,omitempty"`
}

func (x *CafeObject) Reset() {
	*x = CafeObject{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cafe_service_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CafeObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CafeObject) ProtoMessage() {}

func (x *CafeObject) ProtoReflect() protoreflect.Message {
	mi := &file_cafe_service_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CafeObject.ProtoReflect.Descriptor instead.
func (*CafeObject) Descriptor() ([]byte, []int) {
	return file_cafe_service_proto_rawDescGZIP(), []int{13}
}

func (x *CafeObject) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CafeObject) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *CafeObject) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CafeObject) GetNode() []byte {
	if x != nil {
		return x.Node
	}
	return nil
}

type CafeStoreThread struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token      string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Id         string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Ciphertext []byte `protobuf:"bytes,3,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"` // encrypted Thread
}

func (x *CafeStoreThread) Reset() {
	*x = CafeStoreThread{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cafe_service_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CafeStoreThread) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CafeStoreThread) ProtoMessage() {}

func (x *CafeStoreThread) ProtoReflect() protoreflect.Message {
	mi := &file_cafe_service_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CafeStoreThread.ProtoReflect.Descriptor instead.
func (*CafeStoreThread) Descriptor() ([]byte, []int) {
	return file_cafe_service_proto_rawDescGZIP(), []int{14}
}

func (x *CafeStoreThread) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CafeStoreThread) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CafeStoreThread) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

type CafeStoreThreadAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CafeStoreThreadAck) Reset() {
	*x = CafeStoreThreadAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cafe_service_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CafeStoreThreadAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CafeStoreThreadAck) ProtoMessage() {}

func (x *CafeStoreThreadAck) ProtoReflect() protoreflect.Message {
	mi := &file_cafe_service_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CafeStoreThreadAck.ProtoReflect.Descriptor instead.
func (*CafeStoreThreadAck) Descriptor() ([]byte, []int) {
	return file_cafe_service_proto_rawDescGZIP(), []int{15}
}

func (x *CafeStoreThreadAck) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CafeUnstoreThread struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Id    string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CafeUnstoreThread) Reset() {
	*x = CafeUnstoreThread{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cafe_service_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CafeUnstoreThread) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CafeUnstoreThread) ProtoMessage() {}

func (x *CafeUnstoreThread) ProtoReflect() protoreflect.Message {
	mi := &file_cafe_service_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CafeUnstoreThread.ProtoReflect.Descriptor instead.
func (*CafeUnstoreThread) Descriptor() ([]byte, []int) {
	return file_cafe_service_proto_rawDescGZIP(), []int{16}
}

func (x *CafeUnstoreThread) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CafeUnstoreThread) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CafeUnstoreThreadAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CafeUnstoreThreadAck) Reset() {
	*x = CafeUnstoreThreadAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cafe_service_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CafeUnstoreThreadAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CafeUnstoreThreadAck) ProtoMessage() {}

func (x *CafeUnstoreThreadAck) ProtoReflect() protoreflect.Message {
	mi := &file_cafe_service_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CafeUnstoreThreadAck.ProtoReflect.Descriptor instead.
func (*CafeUnstoreThreadAck) Descriptor() ([]byte, []int) {
	return file_cafe_service_proto_rawDescGZIP(), []int{17}
}

func (x *CafeUnstoreThreadAck) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CafePublishVideo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Video *Video `protobuf:"bytes,2,opt,name=video,proto3" json:"video,omitempty"`
	Store bool   `protobuf:"varint,3,opt,name=store,proto3" json:"store,omitempty"`
}

func (x *CafePublishVideo) Reset() {
	*x = CafePublishVideo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cafe_service_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CafePublishVideo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CafePublishVideo) ProtoMessage() {}

func (x *CafePublishVideo) ProtoReflect() protoreflect.Message {
	mi := &file_cafe_service_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CafePublishVideo.ProtoReflect.Descriptor instead.
func (*CafePublishVideo) Descriptor() ([]byte, []int) {
	return file_cafe_service_proto_rawDescGZIP(), []int{18}
}

func (x *CafePublishVideo) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CafePublishVideo) GetVideo() *Video {
	if x != nil {
		return x.Video
	}
	return nil
}

func (x *CafePublishVideo) GetStore() bool {
	if x != nil {
		return x.Store
	}
	return false
}

type CafePublishVideoAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CafePublishVideoAck) Reset() {
	*x = CafePublishVideoAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cafe_service_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CafePublishVideoAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CafePublishVideoAck) ProtoMessage() {}

func (x *CafePublishVideoAck) ProtoReflect() protoreflect.Message {
	mi := &file_cafe_service_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CafePublishVideoAck.ProtoReflect.Descriptor instead.
func (*CafePublishVideoAck) Descriptor() ([]byte, []int) {
	return file_cafe_service_proto_rawDescGZIP(), []int{19}
}

func (x *CafePublishVideoAck) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CafeSendFile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Size int32  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Data []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *CafeSendFile) Reset() {
	*x = CafeSendFile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cafe_service_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CafeSendFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CafeSendFile) ProtoMessage() {}

func (x *CafeSendFile) ProtoReflect() protoreflect.Message {
	mi := &file_cafe_service_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CafeSendFile.ProtoReflect.Descriptor instead.
func (*CafeSendFile) Descriptor() ([]byte, []int) {
	return file_cafe_service_proto_rawDescGZIP(), []int{20}
}

func (x *CafeSendFile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CafeSendFile) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *CafeSendFile) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type CafePublishVideoChunk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string        `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Chunk *VideoChunk   `protobuf:"bytes,2,opt,name=chunk,proto3" json:"chunk,omitempty"`
	File  *CafeSendFile `protobuf:"bytes,3,opt,name=file,proto3" json:"file,omitempty"`
}

func (x *CafePublishVideoChunk) Reset() {
	*x = CafePublishVideoChunk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cafe_service_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CafePublishVideoChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CafePublishVideoChunk) ProtoMessage() {}

func (x *CafePublishVideoChunk) ProtoReflect() protoreflect.Message {
	mi := &file_cafe_service_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CafePublishVideoChunk.ProtoReflect.Descriptor instead.
func (*CafePublishVideoChunk) Descriptor() ([]byte, []int) {
	return file_cafe_service_proto_rawDescGZIP(), []int{21}
}

func (x *CafePublishVideoChunk) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CafePublishVideoChunk) GetChunk() *VideoChunk {
	if x != nil {
		return x.Chunk
	}
	return nil
}

func (x *CafePublishVideoChunk) GetFile() *CafeSendFile {
	if x != nil {
		return x.File
	}
	return nil
}

type CafePublishVideoChunkAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Chunk string `protobuf:"bytes,2,opt,name=chunk,proto3" json:"chunk,omitempty"`
}

func (x *CafePublishVideoChunkAck) Reset() {
	*x = CafePublishVideoChunkAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cafe_service_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CafePublishVideoChunkAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CafePublishVideoChunkAck) ProtoMessage() {}

func (x *CafePublishVideoChunkAck) ProtoReflect() protoreflect.Message {
	mi := &file_cafe_service_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CafePublishVideoChunkAck.ProtoReflect.Descriptor instead.
func (*CafePublishVideoChunkAck) Descriptor() ([]byte, []int) {
	return file_cafe_service_proto_rawDescGZIP(), []int{22}
}

func (x *CafePublishVideoChunkAck) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CafePublishVideoChunkAck) GetChunk() string {
	if x != nil {
		return x.Chunk
	}
	return ""
}

type CafeSyncFile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string    `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	File  *SyncFile `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
}

func (x *CafeSyncFile) Reset() {
	*x = CafeSyncFile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cafe_service_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CafeSyncFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CafeSyncFile) ProtoMessage() {}

func (x *CafeSyncFile) ProtoReflect() protoreflect.Message {
	mi := &file_cafe_service_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CafeSyncFile.ProtoReflect.Descriptor instead.
func (*CafeSyncFile) Descriptor() ([]byte, []int) {
	return file_cafe_service_proto_rawDescGZIP(), []int{23}
}

func (x *CafeSyncFile) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CafeSyncFile) GetFile() *SyncFile {
	if x != nil {
		return x.File
	}
	return nil
}

type CafeSyncFileAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PeerAddress string `protobuf:"bytes,1,opt,name=peerAddress,proto3" json:"peerAddress,omitempty"`
	File        string `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
}

func (x *CafeSyncFileAck) Reset() {
	*x = CafeSyncFileAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cafe_service_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CafeSyncFileAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CafeSyncFileAck) ProtoMessage() {}

func (x *CafeSyncFileAck) ProtoReflect() protoreflect.Message {
	mi := &file_cafe_service_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CafeSyncFileAck.ProtoReflect.Descriptor instead.
func (*CafeSyncFileAck) Descriptor() ([]byte, []int) {
	return file_cafe_service_proto_rawDescGZIP(), []int{24}
}

func (x *CafeSyncFileAck) GetPeerAddress() string {
	if x != nil {
		return x.PeerAddress
	}
	return ""
}

func (x *CafeSyncFileAck) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

type CafeFindIpfsAddr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string     `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Query *IpfsQuery `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *CafeFindIpfsAddr) Reset() {
	*x = CafeFindIpfsAddr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cafe_service_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CafeFindIpfsAddr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CafeFindIpfsAddr) ProtoMessage() {}

func (x *CafeFindIpfsAddr) ProtoReflect() protoreflect.Message {
	mi := &file_cafe_service_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CafeFindIpfsAddr.ProtoReflect.Descriptor instead.
func (*CafeFindIpfsAddr) Descriptor() ([]byte, []int) {
	return file_cafe_service_proto_rawDescGZIP(), []int{25}
}

func (x *CafeFindIpfsAddr) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CafeFindIpfsAddr) GetQuery() *IpfsQuery {
	if x != nil {
		return x.Query
	}
	return nil
}

type CafeFindIpfsAddrAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *IpfsQueryResult `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *CafeFindIpfsAddrAck) Reset() {
	*x = CafeFindIpfsAddrAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cafe_service_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CafeFindIpfsAddrAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CafeFindIpfsAddrAck) ProtoMessage() {}

func (x *CafeFindIpfsAddrAck) ProtoReflect() protoreflect.Message {
	mi := &file_cafe_service_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CafeFindIpfsAddrAck.ProtoReflect.Descriptor instead.
func (*CafeFindIpfsAddrAck) Descriptor() ([]byte, []int) {
	return file_cafe_service_proto_rawDescGZIP(), []int{26}
}

func (x *CafeFindIpfsAddrAck) GetResult() *IpfsQueryResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type CafeDeliverMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Client string `protobuf:"bytes,2,opt,name=client,proto3" json:"client,omitempty"`
	Env    []byte `protobuf:"bytes,3,opt,name=env,proto3" json:"env,omitempty"`
}

func (x *CafeDeliverMessage) Reset() {
	*x = CafeDeliverMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cafe_service_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CafeDeliverMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CafeDeliverMessage) ProtoMessage() {}

func (x *CafeDeliverMessage) ProtoReflect() protoreflect.Message {
	mi := &file_cafe_service_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CafeDeliverMessage.ProtoReflect.Descriptor instead.
func (*CafeDeliverMessage) Descriptor() ([]byte, []int) {
	return file_cafe_service_proto_rawDescGZIP(), []int{27}
}

func (x *CafeDeliverMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CafeDeliverMessage) GetClient() string {
	if x != nil {
		return x.Client
	}
	return ""
}

func (x *CafeDeliverMessage) GetEnv() []byte {
	if x != nil {
		return x.Env
	}
	return nil
}

type CafeCheckMessages struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *CafeCheckMessages) Reset() {
	*x = CafeCheckMessages{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cafe_service_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CafeCheckMessages) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CafeCheckMessages) ProtoMessage() {}

func (x *CafeCheckMessages) ProtoReflect() protoreflect.Message {
	mi := &file_cafe_service_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CafeCheckMessages.ProtoReflect.Descriptor instead.
func (*CafeCheckMessages) Descriptor() ([]byte, []int) {
	return file_cafe_service_proto_rawDescGZIP(), []int{28}
}

func (x *CafeCheckMessages) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type CafeMessages struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Messages []*CafeMessage `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
}

func (x *CafeMessages) Reset() {
	*x = CafeMessages{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cafe_service_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CafeMessages) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CafeMessages) ProtoMessage() {}

func (x *CafeMessages) ProtoReflect() protoreflect.Message {
	mi := &file_cafe_service_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CafeMessages.ProtoReflect.Descriptor instead.
func (*CafeMessages) Descriptor() ([]byte, []int) {
	return file_cafe_service_proto_rawDescGZIP(), []int{29}
}

func (x *CafeMessages) GetMessages() []*CafeMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

type CafeDeleteMessages struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *CafeDeleteMessages) Reset() {
	*x = CafeDeleteMessages{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cafe_service_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CafeDeleteMessages) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CafeDeleteMessages) ProtoMessage() {}

func (x *CafeDeleteMessages) ProtoReflect() protoreflect.Message {
	mi := &file_cafe_service_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CafeDeleteMessages.ProtoReflect.Descriptor instead.
func (*CafeDeleteMessages) Descriptor() ([]byte, []int) {
	return file_cafe_service_proto_rawDescGZIP(), []int{30}
}

func (x *CafeDeleteMessages) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type CafeDeleteMessagesAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	More bool `protobuf:"varint,1,opt,name=more,proto3" json:"more,omitempty"`
}

func (x *CafeDeleteMessagesAck) Reset() {
	*x = CafeDeleteMessagesAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cafe_service_proto_msgTypes[31]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CafeDeleteMessagesAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CafeDeleteMessagesAck) ProtoMessage() {}

func (x *CafeDeleteMessagesAck) ProtoReflect() protoreflect.Message {
	mi := &file_cafe_service_proto_msgTypes[31]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CafeDeleteMessagesAck.ProtoReflect.Descriptor instead.
func (*CafeDeleteMessagesAck) Descriptor() ([]byte, []int) {
	return file_cafe_service_proto_rawDescGZIP(), []int{31}
}

func (x *CafeDeleteMessagesAck) GetMore() bool {
	if x != nil {
		return x.More
	}
	return false
}

var File_cafe_service_proto protoreflect.FileDescriptor

var file_cafe_service_proto_rawDesc = []byte{
	0x0a, 0x12, 0x63, 0x61, 0x66, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0b, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x0b, 0x71, 0x75, 0x65, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x29,
	0x0a, 0x0d, 0x43, 0x61, 0x66, 0x65, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x21, 0x0a, 0x09, 0x43, 0x61, 0x66,
	0x65, 0x4e, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x80, 0x01, 0x0a,
	0x10, 0x43, 0x61, 0x66, 0x65, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x69, 0x67, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x73, 0x69, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22,
	0x2a, 0x0a, 0x12, 0x43, 0x61, 0x66, 0x65, 0x44, 0x65, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x27, 0x0a, 0x15, 0x43,
	0x61, 0x66, 0x65, 0x44, 0x65, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x41, 0x63, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x46, 0x0a, 0x12, 0x43, 0x61, 0x66, 0x65, 0x52, 0x65, 0x66, 0x72,
	0x65, 0x73, 0x68, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x22, 0x42, 0x0a, 0x0f,
	0x43, 0x61, 0x66, 0x65, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x50, 0x65, 0x65, 0x72, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x19, 0x0a, 0x04, 0x70, 0x65, 0x65, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x50, 0x65, 0x65, 0x72, 0x52, 0x04, 0x70, 0x65, 0x65, 0x72,
	0x22, 0x24, 0x0a, 0x12, 0x43, 0x61, 0x66, 0x65, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x50,
	0x65, 0x65, 0x72, 0x41, 0x63, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x35, 0x0a, 0x09, 0x43, 0x61, 0x66, 0x65, 0x53, 0x74,
	0x6f, 0x72, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x69, 0x64,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x63, 0x69, 0x64, 0x73, 0x22, 0x1e, 0x0a,
	0x0c, 0x43, 0x61, 0x66, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x41, 0x63, 0x6b, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x37, 0x0a,
	0x0b, 0x43, 0x61, 0x66, 0x65, 0x55, 0x6e, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x04, 0x63, 0x69, 0x64, 0x73, 0x22, 0x24, 0x0a, 0x0e, 0x43, 0x61, 0x66, 0x65, 0x55, 0x6e,
	0x73, 0x74, 0x6f, 0x72, 0x65, 0x41, 0x63, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x69, 0x64, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x63, 0x69, 0x64, 0x73, 0x22, 0x24, 0x0a, 0x0e,
	0x43, 0x61, 0x66, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x63, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x63, 0x69,
	0x64, 0x73, 0x22, 0x5c, 0x0a, 0x0a, 0x43, 0x61, 0x66, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x63, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x6e, 0x6f, 0x64, 0x65,
	0x22, 0x57, 0x0a, 0x0f, 0x43, 0x61, 0x66, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x54, 0x68, 0x72,
	0x65, 0x61, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x69, 0x70,
	0x68, 0x65, 0x72, 0x74, 0x65, 0x78, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x63,
	0x69, 0x70, 0x68, 0x65, 0x72, 0x74, 0x65, 0x78, 0x74, 0x22, 0x24, 0x0a, 0x12, 0x43, 0x61, 0x66,
	0x65, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x54, 0x68, 0x72, 0x65, 0x61, 0x64, 0x41, 0x63, 0x6b, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x39, 0x0a, 0x11, 0x43, 0x61, 0x66, 0x65, 0x55, 0x6e, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x54, 0x68,
	0x72, 0x65, 0x61, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x26, 0x0a, 0x14, 0x43, 0x61,
	0x66, 0x65, 0x55, 0x6e, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x54, 0x68, 0x72, 0x65, 0x61, 0x64, 0x41,
	0x63, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x5c, 0x0a, 0x10, 0x43, 0x61, 0x66, 0x65, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73,
	0x68, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1c, 0x0a, 0x05,
	0x76, 0x69, 0x64, 0x65, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x56, 0x69,
	0x64, 0x65, 0x6f, 0x52, 0x05, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74,
	0x6f, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x73, 0x74, 0x6f, 0x72, 0x65,
	0x22, 0x25, 0x0a, 0x13, 0x43, 0x61, 0x66, 0x65, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x56,
	0x69, 0x64, 0x65, 0x6f, 0x41, 0x63, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x4a, 0x0a, 0x0c, 0x43, 0x61, 0x66, 0x65, 0x53,
	0x65, 0x6e, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73,
	0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x22, 0x73, 0x0a, 0x15, 0x43, 0x61, 0x66, 0x65, 0x50, 0x75, 0x62, 0x6c, 0x69,
	0x73, 0x68, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x12, 0x21, 0x0a, 0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0b, 0x2e, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x52, 0x05,
	0x63, 0x68, 0x75, 0x6e, 0x6b, 0x12, 0x21, 0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x43, 0x61, 0x66, 0x65, 0x53, 0x65, 0x6e, 0x64, 0x46, 0x69,
	0x6c, 0x65, 0x52, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x22, 0x40, 0x0a, 0x18, 0x43, 0x61, 0x66, 0x65,
	0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x43, 0x68, 0x75, 0x6e,
	0x6b, 0x41, 0x63, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x22, 0x43, 0x0a, 0x0c, 0x43, 0x61,
	0x66, 0x65, 0x53, 0x79, 0x6e, 0x63, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x12, 0x1d, 0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09,
	0x2e, 0x53, 0x79, 0x6e, 0x63, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x22,
	0x47, 0x0a, 0x0f, 0x43, 0x61, 0x66, 0x65, 0x53, 0x79, 0x6e, 0x63, 0x46, 0x69, 0x6c, 0x65, 0x41,
	0x63, 0x6b, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x65, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x65, 0x65, 0x72, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x22, 0x4a, 0x0a, 0x10, 0x43, 0x61, 0x66, 0x65,
	0x46, 0x69, 0x6e, 0x64, 0x49, 0x70, 0x66, 0x73, 0x41, 0x64, 0x64, 0x72, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x12, 0x20, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0a, 0x2e, 0x49, 0x70, 0x66, 0x73, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x05, 0x71,
	0x75, 0x65, 0x72, 0x79, 0x22, 0x3f, 0x0a, 0x13, 0x43, 0x61, 0x66, 0x65, 0x46, 0x69, 0x6e, 0x64,
	0x49, 0x70, 0x66, 0x73, 0x41, 0x64, 0x64, 0x72, 0x41, 0x63, 0x6b, 0x12, 0x28, 0x0a, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x49, 0x70,
	0x66, 0x73, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x4e, 0x0a, 0x12, 0x43, 0x61, 0x66, 0x65, 0x44, 0x65, 0x6c,
	0x69, 0x76, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x6e, 0x76, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x03, 0x65, 0x6e, 0x76, 0x22, 0x29, 0x0a, 0x11, 0x43, 0x61, 0x66, 0x65, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x22, 0x38, 0x0a, 0x0c, 0x43, 0x61, 0x66, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73,
	0x12, 0x28, 0x0a, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x43, 0x61, 0x66, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x52, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x22, 0x2a, 0x0a, 0x12, 0x43, 0x61,
	0x66, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x2b, 0x0a, 0x15, 0x43, 0x61, 0x66, 0x65, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x41, 0x63, 0x6b, 0x12,
	0x12, 0x0a, 0x04, 0x6d, 0x6f, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x6d,
	0x6f, 0x72, 0x65, 0x42, 0x1c, 0x0a, 0x16, 0x73, 0x6a, 0x74, 0x75, 0x2e, 0x6f, 0x70, 0x65, 0x6e,
	0x6e, 0x65, 0x74, 0x2e, 0x74, 0x65, 0x78, 0x74, 0x69, 0x6c, 0x65, 0x70, 0x62, 0x5a, 0x02, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cafe_service_proto_rawDescOnce sync.Once
	file_cafe_service_proto_rawDescData = file_cafe_service_proto_rawDesc
)

func file_cafe_service_proto_rawDescGZIP() []byte {
	file_cafe_service_proto_rawDescOnce.Do(func() {
		file_cafe_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_cafe_service_proto_rawDescData)
	})
	return file_cafe_service_proto_rawDescData
}

var file_cafe_service_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_cafe_service_proto_goTypes = []interface{}{
	(*CafeChallenge)(nil),            // 0: CafeChallenge
	(*CafeNonce)(nil),                // 1: CafeNonce
	(*CafeRegistration)(nil),         // 2: CafeRegistration
	(*CafeDeregistration)(nil),       // 3: CafeDeregistration
	(*CafeDeregistrationAck)(nil),    // 4: CafeDeregistrationAck
	(*CafeRefreshSession)(nil),       // 5: CafeRefreshSession
	(*CafePublishPeer)(nil),          // 6: CafePublishPeer
	(*CafePublishPeerAck)(nil),       // 7: CafePublishPeerAck
	(*CafeStore)(nil),                // 8: CafeStore
	(*CafeStoreAck)(nil),             // 9: CafeStoreAck
	(*CafeUnstore)(nil),              // 10: CafeUnstore
	(*CafeUnstoreAck)(nil),           // 11: CafeUnstoreAck
	(*CafeObjectList)(nil),           // 12: CafeObjectList
	(*CafeObject)(nil),               // 13: CafeObject
	(*CafeStoreThread)(nil),          // 14: CafeStoreThread
	(*CafeStoreThreadAck)(nil),       // 15: CafeStoreThreadAck
	(*CafeUnstoreThread)(nil),        // 16: CafeUnstoreThread
	(*CafeUnstoreThreadAck)(nil),     // 17: CafeUnstoreThreadAck
	(*CafePublishVideo)(nil),         // 18: CafePublishVideo
	(*CafePublishVideoAck)(nil),      // 19: CafePublishVideoAck
	(*CafeSendFile)(nil),             // 20: CafeSendFile
	(*CafePublishVideoChunk)(nil),    // 21: CafePublishVideoChunk
	(*CafePublishVideoChunkAck)(nil), // 22: CafePublishVideoChunkAck
	(*CafeSyncFile)(nil),             // 23: CafeSyncFile
	(*CafeSyncFileAck)(nil),          // 24: CafeSyncFileAck
	(*CafeFindIpfsAddr)(nil),         // 25: CafeFindIpfsAddr
	(*CafeFindIpfsAddrAck)(nil),      // 26: CafeFindIpfsAddrAck
	(*CafeDeliverMessage)(nil),       // 27: CafeDeliverMessage
	(*CafeCheckMessages)(nil),        // 28: CafeCheckMessages
	(*CafeMessages)(nil),             // 29: CafeMessages
	(*CafeDeleteMessages)(nil),       // 30: CafeDeleteMessages
	(*CafeDeleteMessagesAck)(nil),    // 31: CafeDeleteMessagesAck
	(*Peer)(nil),                     // 32: Peer
	(*Video)(nil),                    // 33: Video
	(*VideoChunk)(nil),               // 34: VideoChunk
	(*SyncFile)(nil),                 // 35: SyncFile
	(*IpfsQuery)(nil),                // 36: IpfsQuery
	(*IpfsQueryResult)(nil),          // 37: IpfsQueryResult
	(*CafeMessage)(nil),              // 38: CafeMessage
}
var file_cafe_service_proto_depIdxs = []int32{
	32, // 0: CafePublishPeer.peer:type_name -> Peer
	33, // 1: CafePublishVideo.video:type_name -> Video
	34, // 2: CafePublishVideoChunk.chunk:type_name -> VideoChunk
	20, // 3: CafePublishVideoChunk.file:type_name -> CafeSendFile
	35, // 4: CafeSyncFile.file:type_name -> SyncFile
	36, // 5: CafeFindIpfsAddr.query:type_name -> IpfsQuery
	37, // 6: CafeFindIpfsAddrAck.result:type_name -> IpfsQueryResult
	38, // 7: CafeMessages.messages:type_name -> CafeMessage
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_cafe_service_proto_init() }
func file_cafe_service_proto_init() {
	if File_cafe_service_proto != nil {
		return
	}
	file_model_proto_init()
	file_query_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_cafe_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CafeChallenge); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cafe_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CafeNonce); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cafe_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CafeRegistration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cafe_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CafeDeregistration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cafe_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CafeDeregistrationAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cafe_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CafeRefreshSession); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cafe_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CafePublishPeer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cafe_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CafePublishPeerAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cafe_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CafeStore); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cafe_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CafeStoreAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cafe_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CafeUnstore); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cafe_service_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CafeUnstoreAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cafe_service_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CafeObjectList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cafe_service_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CafeObject); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cafe_service_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CafeStoreThread); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cafe_service_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CafeStoreThreadAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cafe_service_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CafeUnstoreThread); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cafe_service_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CafeUnstoreThreadAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cafe_service_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CafePublishVideo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cafe_service_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CafePublishVideoAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cafe_service_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CafeSendFile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cafe_service_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CafePublishVideoChunk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cafe_service_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CafePublishVideoChunkAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cafe_service_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CafeSyncFile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cafe_service_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CafeSyncFileAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cafe_service_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CafeFindIpfsAddr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cafe_service_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CafeFindIpfsAddrAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cafe_service_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CafeDeliverMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cafe_service_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CafeCheckMessages); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cafe_service_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CafeMessages); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cafe_service_proto_msgTypes[30].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CafeDeleteMessages); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cafe_service_proto_msgTypes[31].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CafeDeleteMessagesAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cafe_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cafe_service_proto_goTypes,
		DependencyIndexes: file_cafe_service_proto_depIdxs,
		MessageInfos:      file_cafe_service_proto_msgTypes,
	}.Build()
	File_cafe_service_proto = out.File
	file_cafe_service_proto_rawDesc = nil
	file_cafe_service_proto_goTypes = nil
	file_cafe_service_proto_depIdxs = nil
}
