// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message_Type int32

const (
	Message_PING                          Message_Type = 0
	Message_PONG                          Message_Type = 1
	Message_THREAD_ENVELOPE               Message_Type = 10
	Message_THREAD_ENVELOPE_ACK           Message_Type = 11
	Message_CAFE_CHALLENGE                Message_Type = 50
	Message_CAFE_NONCE                    Message_Type = 51
	Message_CAFE_REGISTRATION             Message_Type = 52
	Message_CAFE_DEREGISTRATION           Message_Type = 72
	Message_CAFE_DEREGISTRATION_ACK       Message_Type = 73
	Message_CAFE_SESSION                  Message_Type = 53
	Message_CAFE_REFRESH_SESSION          Message_Type = 54
	Message_CAFE_STORE                    Message_Type = 55
	Message_CAFE_STORE_ACK                Message_Type = 59
	Message_CAFE_UNSTORE                  Message_Type = 74
	Message_CAFE_UNSTORE_ACK              Message_Type = 75
	Message_CAFE_OBJECT                   Message_Type = 56
	Message_CAFE_OBJECT_LIST              Message_Type = 57
	Message_CAFE_STORE_THREAD             Message_Type = 58
	Message_CAFE_STORE_THREAD_ACK         Message_Type = 76
	Message_CAFE_UNSTORE_THREAD           Message_Type = 77
	Message_CAFE_UNSTORE_THREAD_ACK       Message_Type = 78
	Message_CAFE_DELIVER_MESSAGE          Message_Type = 60
	Message_CAFE_CHECK_MESSAGES           Message_Type = 61
	Message_CAFE_MESSAGES                 Message_Type = 62
	Message_CAFE_DELETE_MESSAGES          Message_Type = 63
	Message_CAFE_DELETE_MESSAGES_ACK      Message_Type = 64
	Message_CAFE_YOU_HAVE_MAIL            Message_Type = 65
	Message_CAFE_PUBLISH_PEER             Message_Type = 66
	Message_CAFE_PUBLISH_PEER_ACK         Message_Type = 67
	Message_CAFE_QUERY                    Message_Type = 70
	Message_CAFE_QUERY_RES                Message_Type = 71
	Message_CAFE_PUBLISH_VIDEO            Message_Type = 200
	Message_CAFE_PUBLISH_VIDEO_ACK        Message_Type = 201
	Message_CAFE_PUBLISH_VIDEO_CHUNK      Message_Type = 202
	Message_CAFE_PUBLISH_VIDEO_CHUNK_ACK  Message_Type = 203
	Message_CAFE_SYNC_FILE                Message_Type = 204
	Message_CAFE_SYNC_FILE_ACK            Message_Type = 205
	Message_CAFE_FIND_IPFS_ADDR           Message_Type = 206
	Message_CAFE_FIND_IPFS_ADDR_ACK       Message_Type = 207
	Message_CAFE_PUBSUB_QUERY             Message_Type = 102
	Message_CAFE_PUBSUB_QUERY_RES         Message_Type = 103
	Message_ERROR                         Message_Type = 500
	Message_CAFE_CONTACT_QUERY            Message_Type = 68  // Deprecated: Do not use.
	Message_CAFE_CONTACT_QUERY_RES        Message_Type = 69  // Deprecated: Do not use.
	Message_CAFE_PUBSUB_CONTACT_QUERY     Message_Type = 100 // Deprecated: Do not use.
	Message_CAFE_PUBSUB_CONTACT_QUERY_RES Message_Type = 101 // Deprecated: Do not use.
)

var Message_Type_name = map[int32]string{
	0:   "PING",
	1:   "PONG",
	10:  "THREAD_ENVELOPE",
	11:  "THREAD_ENVELOPE_ACK",
	50:  "CAFE_CHALLENGE",
	51:  "CAFE_NONCE",
	52:  "CAFE_REGISTRATION",
	72:  "CAFE_DEREGISTRATION",
	73:  "CAFE_DEREGISTRATION_ACK",
	53:  "CAFE_SESSION",
	54:  "CAFE_REFRESH_SESSION",
	55:  "CAFE_STORE",
	59:  "CAFE_STORE_ACK",
	74:  "CAFE_UNSTORE",
	75:  "CAFE_UNSTORE_ACK",
	56:  "CAFE_OBJECT",
	57:  "CAFE_OBJECT_LIST",
	58:  "CAFE_STORE_THREAD",
	76:  "CAFE_STORE_THREAD_ACK",
	77:  "CAFE_UNSTORE_THREAD",
	78:  "CAFE_UNSTORE_THREAD_ACK",
	60:  "CAFE_DELIVER_MESSAGE",
	61:  "CAFE_CHECK_MESSAGES",
	62:  "CAFE_MESSAGES",
	63:  "CAFE_DELETE_MESSAGES",
	64:  "CAFE_DELETE_MESSAGES_ACK",
	65:  "CAFE_YOU_HAVE_MAIL",
	66:  "CAFE_PUBLISH_PEER",
	67:  "CAFE_PUBLISH_PEER_ACK",
	70:  "CAFE_QUERY",
	71:  "CAFE_QUERY_RES",
	200: "CAFE_PUBLISH_VIDEO",
	201: "CAFE_PUBLISH_VIDEO_ACK",
	202: "CAFE_PUBLISH_VIDEO_CHUNK",
	203: "CAFE_PUBLISH_VIDEO_CHUNK_ACK",
	204: "CAFE_SYNC_FILE",
	205: "CAFE_SYNC_FILE_ACK",
	206: "CAFE_FIND_IPFS_ADDR",
	207: "CAFE_FIND_IPFS_ADDR_ACK",
	102: "CAFE_PUBSUB_QUERY",
	103: "CAFE_PUBSUB_QUERY_RES",
	500: "ERROR",
	68:  "CAFE_CONTACT_QUERY",
	69:  "CAFE_CONTACT_QUERY_RES",
	100: "CAFE_PUBSUB_CONTACT_QUERY",
	101: "CAFE_PUBSUB_CONTACT_QUERY_RES",
}

var Message_Type_value = map[string]int32{
	"PING":                          0,
	"PONG":                          1,
	"THREAD_ENVELOPE":               10,
	"THREAD_ENVELOPE_ACK":           11,
	"CAFE_CHALLENGE":                50,
	"CAFE_NONCE":                    51,
	"CAFE_REGISTRATION":             52,
	"CAFE_DEREGISTRATION":           72,
	"CAFE_DEREGISTRATION_ACK":       73,
	"CAFE_SESSION":                  53,
	"CAFE_REFRESH_SESSION":          54,
	"CAFE_STORE":                    55,
	"CAFE_STORE_ACK":                59,
	"CAFE_UNSTORE":                  74,
	"CAFE_UNSTORE_ACK":              75,
	"CAFE_OBJECT":                   56,
	"CAFE_OBJECT_LIST":              57,
	"CAFE_STORE_THREAD":             58,
	"CAFE_STORE_THREAD_ACK":         76,
	"CAFE_UNSTORE_THREAD":           77,
	"CAFE_UNSTORE_THREAD_ACK":       78,
	"CAFE_DELIVER_MESSAGE":          60,
	"CAFE_CHECK_MESSAGES":           61,
	"CAFE_MESSAGES":                 62,
	"CAFE_DELETE_MESSAGES":          63,
	"CAFE_DELETE_MESSAGES_ACK":      64,
	"CAFE_YOU_HAVE_MAIL":            65,
	"CAFE_PUBLISH_PEER":             66,
	"CAFE_PUBLISH_PEER_ACK":         67,
	"CAFE_QUERY":                    70,
	"CAFE_QUERY_RES":                71,
	"CAFE_PUBLISH_VIDEO":            200,
	"CAFE_PUBLISH_VIDEO_ACK":        201,
	"CAFE_PUBLISH_VIDEO_CHUNK":      202,
	"CAFE_PUBLISH_VIDEO_CHUNK_ACK":  203,
	"CAFE_SYNC_FILE":                204,
	"CAFE_SYNC_FILE_ACK":            205,
	"CAFE_FIND_IPFS_ADDR":           206,
	"CAFE_FIND_IPFS_ADDR_ACK":       207,
	"CAFE_PUBSUB_QUERY":             102,
	"CAFE_PUBSUB_QUERY_RES":         103,
	"ERROR":                         500,
	"CAFE_CONTACT_QUERY":            68,
	"CAFE_CONTACT_QUERY_RES":        69,
	"CAFE_PUBSUB_CONTACT_QUERY":     100,
	"CAFE_PUBSUB_CONTACT_QUERY_RES": 101,
}

func (x Message_Type) String() string {
	return proto.EnumName(Message_Type_name, int32(x))
}

func (Message_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0, 0}
}

type Message struct {
	Type                 Message_Type `protobuf:"varint,1,opt,name=type,proto3,enum=Message_Type" json:"type,omitempty"`
	Payload              *any.Any     `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Request              int32        `protobuf:"varint,3,opt,name=request,proto3" json:"request,omitempty"`
	Response             bool         `protobuf:"varint,4,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetType() Message_Type {
	if m != nil {
		return m.Type
	}
	return Message_PING
}

func (m *Message) GetPayload() *any.Any {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *Message) GetRequest() int32 {
	if m != nil {
		return m.Request
	}
	return 0
}

func (m *Message) GetResponse() bool {
	if m != nil {
		return m.Response
	}
	return false
}

type Envelope struct {
	Message              *Message `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Sig                  []byte   `protobuf:"bytes,2,opt,name=sig,proto3" json:"sig,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Envelope) Reset()         { *m = Envelope{} }
func (m *Envelope) String() string { return proto.CompactTextString(m) }
func (*Envelope) ProtoMessage()    {}
func (*Envelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *Envelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Envelope.Unmarshal(m, b)
}
func (m *Envelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Envelope.Marshal(b, m, deterministic)
}
func (m *Envelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Envelope.Merge(m, src)
}
func (m *Envelope) XXX_Size() int {
	return xxx_messageInfo_Envelope.Size(m)
}
func (m *Envelope) XXX_DiscardUnknown() {
	xxx_messageInfo_Envelope.DiscardUnknown(m)
}

var xxx_messageInfo_Envelope proto.InternalMessageInfo

func (m *Envelope) GetMessage() *Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *Envelope) GetSig() []byte {
	if m != nil {
		return m.Sig
	}
	return nil
}

type Error struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterEnum("Message_Type", Message_Type_name, Message_Type_value)
	proto.RegisterType((*Message)(nil), "Message")
	proto.RegisterType((*Envelope)(nil), "Envelope")
	proto.RegisterType((*Error)(nil), "Error")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 743 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x54, 0x6d, 0x8f, 0xda, 0x46,
	0x10, 0xae, 0xef, 0xb8, 0x1e, 0x99, 0x0b, 0x97, 0xcd, 0xe4, 0x72, 0xe7, 0x23, 0xa4, 0xe2, 0x90,
	0x2a, 0xf1, 0xc9, 0x91, 0x48, 0xd3, 0xf7, 0x97, 0x18, 0x7b, 0xc1, 0x0e, 0xc6, 0xa6, 0x6b, 0x83,
	0x74, 0xfd, 0x62, 0x41, 0x6f, 0x83, 0x52, 0x51, 0xec, 0x02, 0x57, 0x95, 0x7f, 0xd8, 0xd7, 0xf4,
	0x47, 0xf4, 0x2f, 0xf4, 0x07, 0x54, 0x1e, 0xdb, 0x2b, 0x68, 0x92, 0x6f, 0x3b, 0xcf, 0xf3, 0xcc,
	0x33, 0x3b, 0xb3, 0xf6, 0x40, 0xed, 0x47, 0xb9, 0x5e, 0x4f, 0xe7, 0xd2, 0x48, 0x57, 0xc9, 0x26,
	0xa9, 0x5f, 0xce, 0x93, 0x64, 0xbe, 0x90, 0x4f, 0x28, 0x9a, 0xdd, 0xbe, 0x7c, 0x32, 0x5d, 0x6e,
	0x73, 0xaa, 0xf5, 0xcf, 0x1d, 0x38, 0x1e, 0xe6, 0x62, 0xbc, 0x82, 0xca, 0x66, 0x9b, 0x4a, 0x5d,
	0x6b, 0x6a, 0xed, 0xd3, 0x4e, 0xcd, 0x28, 0x70, 0x23, 0xda, 0xa6, 0x52, 0x10, 0x85, 0x06, 0x1c,
	0xa7, 0xd3, 0xed, 0x22, 0x99, 0xde, 0xe8, 0x07, 0x4d, 0xad, 0x7d, 0xd2, 0x39, 0x33, 0x72, 0x6f,
	0xa3, 0xf4, 0x36, 0xcc, 0xe5, 0x56, 0x94, 0x22, 0xd4, 0xe1, 0x78, 0x25, 0x7f, 0xba, 0x95, 0xeb,
	0x8d, 0x7e, 0xd8, 0xd4, 0xda, 0x47, 0xa2, 0x0c, 0xb1, 0x0e, 0xd5, 0x95, 0x5c, 0xa7, 0xc9, 0x72,
	0x2d, 0xf5, 0x4a, 0x53, 0x6b, 0x57, 0x85, 0x8a, 0x5b, 0xaf, 0xab, 0x50, 0xc9, 0x8a, 0x62, 0x15,
	0x2a, 0x23, 0xd7, 0xef, 0xb3, 0xf7, 0xe8, 0x14, 0xf8, 0x7d, 0xa6, 0xe1, 0x03, 0xb8, 0x17, 0x39,
	0x82, 0x9b, 0x76, 0xcc, 0xfd, 0x09, 0xf7, 0x82, 0x11, 0x67, 0x80, 0x17, 0xf0, 0xe0, 0x7f, 0x60,
	0x6c, 0x5a, 0x03, 0x76, 0x82, 0x08, 0xa7, 0x96, 0xd9, 0xe3, 0xb1, 0xe5, 0x98, 0x9e, 0xc7, 0xfd,
	0x3e, 0x67, 0x1d, 0x3c, 0x05, 0x20, 0xcc, 0x0f, 0x7c, 0x8b, 0xb3, 0xa7, 0xf8, 0x10, 0xee, 0x53,
	0x2c, 0x78, 0xdf, 0x0d, 0x23, 0x61, 0x46, 0x6e, 0xe0, 0xb3, 0x8f, 0x32, 0x4f, 0x82, 0x6d, 0xbe,
	0x47, 0x38, 0xf8, 0x08, 0x2e, 0xde, 0x42, 0x50, 0x41, 0x17, 0x19, 0xdc, 0x25, 0x32, 0xe4, 0x61,
	0x98, 0xc9, 0x9f, 0xa1, 0x0e, 0x67, 0x85, 0x7d, 0x4f, 0xf0, 0xd0, 0x51, 0xcc, 0xc7, 0xea, 0x22,
	0x61, 0x14, 0x08, 0xce, 0x3e, 0x51, 0x97, 0xa5, 0x98, 0xfc, 0xbe, 0x50, 0x7e, 0x63, 0x3f, 0x57,
	0xbd, 0xc0, 0x33, 0x60, 0xbb, 0x08, 0xe9, 0x06, 0x78, 0x0f, 0x4e, 0x08, 0x0d, 0xba, 0x2f, 0xb8,
	0x15, 0xb1, 0x4f, 0x95, 0x2c, 0x07, 0x62, 0xcf, 0x0d, 0x23, 0xf6, 0x99, 0xea, 0x35, 0x4f, 0xcd,
	0x67, 0xc6, 0x3e, 0xc7, 0x4b, 0x78, 0xf8, 0x06, 0x4c, 0xc6, 0x9e, 0x1a, 0x43, 0x59, 0xae, 0xc8,
	0x19, 0xaa, 0x31, 0xec, 0x13, 0x94, 0xe5, 0xab, 0xa6, 0x6d, 0xee, 0xb9, 0x13, 0x2e, 0xe2, 0x21,
	0x0f, 0x43, 0xb3, 0xcf, 0xd9, 0x97, 0xca, 0xcf, 0x72, 0xb8, 0x35, 0x28, 0xf1, 0x90, 0x7d, 0x85,
	0xf7, 0xa1, 0x46, 0x84, 0x82, 0xbe, 0xde, 0x75, 0xe1, 0xd1, 0x0e, 0xf3, 0x0d, 0x36, 0x40, 0x7f,
	0x1b, 0x43, 0xd5, 0x9f, 0xe3, 0x39, 0x20, 0xb1, 0xd7, 0xc1, 0x38, 0x76, 0xcc, 0x09, 0x8f, 0x87,
	0xa6, 0xeb, 0x31, 0x53, 0x75, 0x3f, 0x1a, 0x77, 0x3d, 0x37, 0x74, 0xe2, 0x11, 0xe7, 0x82, 0x75,
	0x55, 0xf7, 0xbb, 0x30, 0x39, 0x59, 0xea, 0x89, 0xbe, 0x1d, 0x73, 0x71, 0xcd, 0x7a, 0xea, 0x89,
	0x28, 0x8e, 0x05, 0x0f, 0x59, 0x1f, 0x2f, 0x8a, 0x6a, 0x65, 0xfa, 0xc4, 0xb5, 0x79, 0xc0, 0x7e,
	0xd5, 0xf0, 0x11, 0x9c, 0xbf, 0x49, 0x90, 0xf1, 0x6f, 0x1a, 0x3e, 0x2e, 0x3a, 0xd8, 0x27, 0x2d,
	0x67, 0xec, 0x0f, 0xd8, 0xef, 0x1a, 0x5e, 0x41, 0xe3, 0x5d, 0x34, 0x39, 0xfc, 0x91, 0xfd, 0x09,
	0xc5, 0xe7, 0x72, 0xed, 0x5b, 0x71, 0xcf, 0xf5, 0x38, 0xfb, 0x53, 0x53, 0x97, 0x51, 0x20, 0xa9,
	0xff, 0xd2, 0x50, 0x2f, 0xe6, 0xde, 0x73, 0x7d, 0x3b, 0x76, 0x47, 0xbd, 0x30, 0x36, 0x6d, 0x5b,
	0xb0, 0xd7, 0x1a, 0x36, 0x8a, 0x87, 0xdc, 0x67, 0x28, 0xef, 0x6f, 0x6d, 0x77, 0x66, 0xe1, 0xb8,
	0x5b, 0x0c, 0xe2, 0xe5, 0xee, 0xcc, 0x14, 0x4c, 0xf3, 0x98, 0x23, 0xc0, 0x11, 0x17, 0x22, 0x10,
	0xec, 0xdf, 0x43, 0xac, 0x17, 0xd7, 0xb1, 0x02, 0x3f, 0x32, 0xad, 0xa8, 0x48, 0xb7, 0xeb, 0x07,
	0x55, 0x0d, 0x3f, 0x28, 0xc6, 0xb3, 0xc7, 0x91, 0x07, 0x27, 0xfe, 0x0a, 0x2e, 0x77, 0x4b, 0xec,
	0x5b, 0xdc, 0x90, 0xe4, 0x43, 0x78, 0xfc, 0x4e, 0x09, 0x39, 0xc9, 0x4c, 0xd6, 0x7a, 0x0e, 0x55,
	0xbe, 0xfc, 0x59, 0x2e, 0x92, 0x54, 0x62, 0x0b, 0x8e, 0x8b, 0xed, 0x48, 0x8b, 0xee, 0xa4, 0x53,
	0x2d, 0x17, 0x9d, 0x28, 0x09, 0x64, 0x70, 0xb8, 0x7e, 0x35, 0xa7, 0x15, 0x77, 0x57, 0x64, 0xc7,
	0xd6, 0x33, 0x38, 0xe2, 0xab, 0x55, 0xb2, 0x42, 0x84, 0xca, 0xf7, 0xc9, 0x4d, 0x9e, 0x5b, 0x13,
	0x74, 0xce, 0xb6, 0x5c, 0x69, 0x99, 0xa5, 0xdc, 0x51, 0x46, 0xdd, 0x06, 0x9c, 0xaf, 0x7f, 0xd8,
	0xdc, 0x1a, 0x49, 0x2a, 0x97, 0x4b, 0xb9, 0x31, 0x36, 0xf2, 0x97, 0xcd, 0xab, 0x85, 0x4c, 0x67,
	0xdf, 0x1d, 0xa4, 0xb3, 0xd9, 0xfb, 0xb4, 0x34, 0x9f, 0xfe, 0x17, 0x00, 0x00, 0xff, 0xff, 0xa5,
	0x5e, 0xc4, 0xa6, 0xaf, 0x05, 0x00, 0x00,
}
