// Code generated by protoc-gen-go. DO NOT EDIT.
// source: multicast.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MulticastPacket_Type int32

const (
	MulticastPacket_META MulticastPacket_Type = 0
	MulticastPacket_DATA MulticastPacket_Type = 1
	MulticastPacket_END  MulticastPacket_Type = 2
)

var MulticastPacket_Type_name = map[int32]string{
	0: "META",
	1: "DATA",
	2: "END",
}

var MulticastPacket_Type_value = map[string]int32{
	"META": 0,
	"DATA": 1,
	"END":  2,
}

func (x MulticastPacket_Type) String() string {
	return proto.EnumName(MulticastPacket_Type_name, int32(x))
}

func (MulticastPacket_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_eedbde62517e047e, []int{0, 0}
}

type MulticastMeta_Type int32

const (
	MulticastMeta_FILE MulticastMeta_Type = 0
	MulticastMeta_IMG  MulticastMeta_Type = 1
)

var MulticastMeta_Type_name = map[int32]string{
	0: "FILE",
	1: "IMG",
}

var MulticastMeta_Type_value = map[string]int32{
	"FILE": 0,
	"IMG":  1,
}

func (x MulticastMeta_Type) String() string {
	return proto.EnumName(MulticastMeta_Type_name, int32(x))
}

func (MulticastMeta_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_eedbde62517e047e, []int{1, 0}
}

type MulticastPacket struct {
	Type                 MulticastPacket_Type `protobuf:"varint,1,opt,name=type,proto3,enum=MulticastPacket_Type" json:"type,omitempty"`
	Payload              *any.Any             `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *MulticastPacket) Reset()         { *m = MulticastPacket{} }
func (m *MulticastPacket) String() string { return proto.CompactTextString(m) }
func (*MulticastPacket) ProtoMessage()    {}
func (*MulticastPacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_eedbde62517e047e, []int{0}
}

func (m *MulticastPacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MulticastPacket.Unmarshal(m, b)
}
func (m *MulticastPacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MulticastPacket.Marshal(b, m, deterministic)
}
func (m *MulticastPacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MulticastPacket.Merge(m, src)
}
func (m *MulticastPacket) XXX_Size() int {
	return xxx_messageInfo_MulticastPacket.Size(m)
}
func (m *MulticastPacket) XXX_DiscardUnknown() {
	xxx_messageInfo_MulticastPacket.DiscardUnknown(m)
}

var xxx_messageInfo_MulticastPacket proto.InternalMessageInfo

func (m *MulticastPacket) GetType() MulticastPacket_Type {
	if m != nil {
		return m.Type
	}
	return MulticastPacket_META
}

func (m *MulticastPacket) GetPayload() *any.Any {
	if m != nil {
		return m.Payload
	}
	return nil
}

type MulticastMeta struct {
	Type                 MulticastMeta_Type   `protobuf:"varint,1,opt,name=type,proto3,enum=MulticastMeta_Type" json:"type,omitempty"`
	Id                   string               `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string               `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Sender               string               `protobuf:"bytes,4,opt,name=sender,proto3" json:"sender,omitempty"`
	FileSize             int32                `protobuf:"varint,5,opt,name=fileSize,proto3" json:"fileSize,omitempty"`
	ThreadId             string               `protobuf:"bytes,6,opt,name=threadId,proto3" json:"threadId,omitempty"`
	SendTime             *timestamp.Timestamp `protobuf:"bytes,7,opt,name=sendTime,proto3" json:"sendTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *MulticastMeta) Reset()         { *m = MulticastMeta{} }
func (m *MulticastMeta) String() string { return proto.CompactTextString(m) }
func (*MulticastMeta) ProtoMessage()    {}
func (*MulticastMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_eedbde62517e047e, []int{1}
}

func (m *MulticastMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MulticastMeta.Unmarshal(m, b)
}
func (m *MulticastMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MulticastMeta.Marshal(b, m, deterministic)
}
func (m *MulticastMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MulticastMeta.Merge(m, src)
}
func (m *MulticastMeta) XXX_Size() int {
	return xxx_messageInfo_MulticastMeta.Size(m)
}
func (m *MulticastMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_MulticastMeta.DiscardUnknown(m)
}

var xxx_messageInfo_MulticastMeta proto.InternalMessageInfo

func (m *MulticastMeta) GetType() MulticastMeta_Type {
	if m != nil {
		return m.Type
	}
	return MulticastMeta_FILE
}

func (m *MulticastMeta) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MulticastMeta) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MulticastMeta) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *MulticastMeta) GetFileSize() int32 {
	if m != nil {
		return m.FileSize
	}
	return 0
}

func (m *MulticastMeta) GetThreadId() string {
	if m != nil {
		return m.ThreadId
	}
	return ""
}

func (m *MulticastMeta) GetSendTime() *timestamp.Timestamp {
	if m != nil {
		return m.SendTime
	}
	return nil
}

type MulticastData struct {
	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	// Note:
	//    Shard number and parity number is required by reed solomon decoder.
	//    They should be contained in every data packet cause we do not know which of them would be lost.
	ShardNum             int32    `protobuf:"varint,3,opt,name=shardNum,proto3" json:"shardNum,omitempty"`
	ParityNum            int32    `protobuf:"varint,4,opt,name=parityNum,proto3" json:"parityNum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MulticastData) Reset()         { *m = MulticastData{} }
func (m *MulticastData) String() string { return proto.CompactTextString(m) }
func (*MulticastData) ProtoMessage()    {}
func (*MulticastData) Descriptor() ([]byte, []int) {
	return fileDescriptor_eedbde62517e047e, []int{2}
}

func (m *MulticastData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MulticastData.Unmarshal(m, b)
}
func (m *MulticastData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MulticastData.Marshal(b, m, deterministic)
}
func (m *MulticastData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MulticastData.Merge(m, src)
}
func (m *MulticastData) XXX_Size() int {
	return xxx_messageInfo_MulticastData.Size(m)
}
func (m *MulticastData) XXX_DiscardUnknown() {
	xxx_messageInfo_MulticastData.DiscardUnknown(m)
}

var xxx_messageInfo_MulticastData proto.InternalMessageInfo

func (m *MulticastData) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MulticastData) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *MulticastData) GetShardNum() int32 {
	if m != nil {
		return m.ShardNum
	}
	return 0
}

func (m *MulticastData) GetParityNum() int32 {
	if m != nil {
		return m.ParityNum
	}
	return 0
}

type MulticastEnd struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MulticastEnd) Reset()         { *m = MulticastEnd{} }
func (m *MulticastEnd) String() string { return proto.CompactTextString(m) }
func (*MulticastEnd) ProtoMessage()    {}
func (*MulticastEnd) Descriptor() ([]byte, []int) {
	return fileDescriptor_eedbde62517e047e, []int{3}
}

func (m *MulticastEnd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MulticastEnd.Unmarshal(m, b)
}
func (m *MulticastEnd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MulticastEnd.Marshal(b, m, deterministic)
}
func (m *MulticastEnd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MulticastEnd.Merge(m, src)
}
func (m *MulticastEnd) XXX_Size() int {
	return xxx_messageInfo_MulticastEnd.Size(m)
}
func (m *MulticastEnd) XXX_DiscardUnknown() {
	xxx_messageInfo_MulticastEnd.DiscardUnknown(m)
}

var xxx_messageInfo_MulticastEnd proto.InternalMessageInfo

func (m *MulticastEnd) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterEnum("MulticastPacket_Type", MulticastPacket_Type_name, MulticastPacket_Type_value)
	proto.RegisterEnum("MulticastMeta_Type", MulticastMeta_Type_name, MulticastMeta_Type_value)
	proto.RegisterType((*MulticastPacket)(nil), "MulticastPacket")
	proto.RegisterType((*MulticastMeta)(nil), "MulticastMeta")
	proto.RegisterType((*MulticastData)(nil), "MulticastData")
	proto.RegisterType((*MulticastEnd)(nil), "MulticastEnd")
}

func init() { proto.RegisterFile("multicast.proto", fileDescriptor_eedbde62517e047e) }

var fileDescriptor_eedbde62517e047e = []byte{
	// 397 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x51, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xed, 0xba, 0xce, 0x47, 0x87, 0xd2, 0x5a, 0x0b, 0x54, 0x6e, 0x54, 0x41, 0x64, 0x0e, 0x84,
	0xcb, 0x56, 0x2a, 0x12, 0xf7, 0xa0, 0x18, 0x14, 0x09, 0x57, 0xc8, 0xf8, 0xc4, 0x6d, 0xdd, 0x9d,
	0xb6, 0x0b, 0xfe, 0x58, 0xd9, 0x63, 0x09, 0xf3, 0x2f, 0xf8, 0xc5, 0x20, 0x6f, 0x62, 0x37, 0x4d,
	0x6f, 0xf3, 0xe6, 0x3d, 0xef, 0x9b, 0xf7, 0x0c, 0xa7, 0x79, 0x93, 0x91, 0xbe, 0x91, 0x35, 0x09,
	0x53, 0x95, 0x54, 0xce, 0xde, 0xdc, 0x95, 0xe5, 0x5d, 0x86, 0x97, 0x16, 0xa5, 0xcd, 0xed, 0x25,
	0xe9, 0x1c, 0x6b, 0x92, 0xb9, 0xd9, 0x0a, 0xce, 0xf7, 0x05, 0xb2, 0x68, 0x37, 0x54, 0xf0, 0x97,
	0xc1, 0x69, 0xd4, 0xbf, 0xf7, 0x4d, 0xde, 0xfc, 0x42, 0xe2, 0xef, 0xc1, 0xa5, 0xd6, 0xa0, 0xcf,
	0xe6, 0x6c, 0x71, 0x72, 0xf5, 0x4a, 0xec, 0xf1, 0x22, 0x69, 0x0d, 0xc6, 0x56, 0xc2, 0x05, 0x4c,
	0x8c, 0x6c, 0xb3, 0x52, 0x2a, 0xdf, 0x99, 0xb3, 0xc5, 0xb3, 0xab, 0x97, 0x62, 0xe3, 0x25, 0x7a,
	0x2f, 0xb1, 0x2c, 0xda, 0xb8, 0x17, 0x05, 0x6f, 0xc1, 0xed, 0xbe, 0xe6, 0x53, 0x70, 0xa3, 0x30,
	0x59, 0x7a, 0x07, 0xdd, 0xb4, 0x5a, 0x26, 0x4b, 0x8f, 0xf1, 0x09, 0x1c, 0x86, 0xd7, 0x2b, 0xcf,
	0x09, 0xfe, 0x31, 0x78, 0x3e, 0x78, 0x46, 0x48, 0x92, 0xbf, 0x7b, 0x74, 0xd1, 0x0b, 0xf1, 0x88,
	0xdd, 0xbd, 0xe7, 0x04, 0x1c, 0xbd, 0x39, 0xe5, 0x28, 0x76, 0xb4, 0xe2, 0x1c, 0xdc, 0x42, 0xe6,
	0xe8, 0x1f, 0xda, 0x8d, 0x9d, 0xf9, 0x19, 0x8c, 0x6b, 0x2c, 0x14, 0x56, 0xbe, 0x6b, 0xb7, 0x5b,
	0xc4, 0x67, 0x30, 0xbd, 0xd5, 0x19, 0x7e, 0xd7, 0x7f, 0xd0, 0x1f, 0xcd, 0xd9, 0x62, 0x14, 0x0f,
	0xb8, 0xe3, 0xe8, 0xbe, 0x42, 0xa9, 0xd6, 0xca, 0x1f, 0xdb, 0xaf, 0x06, 0xcc, 0x3f, 0xc2, 0xb4,
	0x7b, 0x21, 0xd1, 0x39, 0xfa, 0x13, 0x5b, 0xc2, 0xec, 0x49, 0x09, 0x49, 0xff, 0x47, 0xe2, 0x41,
	0x1b, 0x9c, 0x3f, 0x74, 0xf1, 0x79, 0xfd, 0x35, 0xf4, 0x0e, 0xba, 0x06, 0xd6, 0xd1, 0x17, 0x8f,
	0x05, 0xf9, 0x4e, 0x01, 0x2b, 0x49, 0x72, 0x9b, 0x8b, 0xed, 0xe6, 0x52, 0x92, 0xa4, 0x4d, 0x7a,
	0x1c, 0xdb, 0xb9, 0xbb, 0xb1, 0xbe, 0x97, 0x95, 0xba, 0x6e, 0x72, 0x9b, 0x77, 0x14, 0x0f, 0x98,
	0x5f, 0xc0, 0x91, 0x91, 0x95, 0xa6, 0xb6, 0x23, 0x5d, 0x4b, 0x3e, 0x2c, 0x82, 0xd7, 0x70, 0x3c,
	0xd8, 0x85, 0x85, 0xda, 0x77, 0xfb, 0x74, 0x01, 0x67, 0xf5, 0x4f, 0x6a, 0x44, 0x69, 0xb0, 0x28,
	0x90, 0x04, 0xe1, 0x6f, 0xd2, 0x19, 0x9a, 0xf4, 0x87, 0x63, 0xd2, 0x74, 0x6c, 0x53, 0x7e, 0xf8,
	0x1f, 0x00, 0x00, 0xff, 0xff, 0x8a, 0xa9, 0x3d, 0xd0, 0x98, 0x02, 0x00, 0x00,
}
