// Code generated by protoc-gen-go. DO NOT EDIT.
// source: record_service.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RecordReport struct {
	Key                  string               `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Start                *timestamp.Timestamp `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"`
	End                  *timestamp.Timestamp `protobuf:"bytes,3,opt,name=end,proto3" json:"end,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *RecordReport) Reset()         { *m = RecordReport{} }
func (m *RecordReport) String() string { return proto.CompactTextString(m) }
func (*RecordReport) ProtoMessage()    {}
func (*RecordReport) Descriptor() ([]byte, []int) {
	return fileDescriptor_239c48d605fbe3ac, []int{0}
}

func (m *RecordReport) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecordReport.Unmarshal(m, b)
}
func (m *RecordReport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecordReport.Marshal(b, m, deterministic)
}
func (m *RecordReport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecordReport.Merge(m, src)
}
func (m *RecordReport) XXX_Size() int {
	return xxx_messageInfo_RecordReport.Size(m)
}
func (m *RecordReport) XXX_DiscardUnknown() {
	xxx_messageInfo_RecordReport.DiscardUnknown(m)
}

var xxx_messageInfo_RecordReport proto.InternalMessageInfo

func (m *RecordReport) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *RecordReport) GetStart() *timestamp.Timestamp {
	if m != nil {
		return m.Start
	}
	return nil
}

func (m *RecordReport) GetEnd() *timestamp.Timestamp {
	if m != nil {
		return m.End
	}
	return nil
}

func init() {
	proto.RegisterType((*RecordReport)(nil), "RecordReport")
}

func init() { proto.RegisterFile("record_service.proto", fileDescriptor_239c48d605fbe3ac) }

var fileDescriptor_239c48d605fbe3ac = []byte{
	// 180 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0xcc, 0xc1, 0x0a, 0x82, 0x40,
	0x10, 0xc6, 0x71, 0x56, 0x29, 0x68, 0xeb, 0x10, 0x12, 0x21, 0x12, 0x24, 0x9d, 0x3c, 0xc4, 0x1a,
	0xf5, 0x06, 0x3d, 0xc2, 0xd2, 0xa9, 0x4b, 0xb8, 0x3a, 0x89, 0xa5, 0xce, 0xb2, 0x3b, 0x46, 0xdd,
	0x7a, 0xf4, 0xd0, 0xc5, 0x73, 0xb7, 0x19, 0xf8, 0x7d, 0x7f, 0xbe, 0x32, 0x90, 0xa3, 0x29, 0x6e,
	0x16, 0xcc, 0xab, 0xca, 0x41, 0x68, 0x83, 0x84, 0xd1, 0xb6, 0x44, 0x2c, 0x6b, 0x48, 0x87, 0x4f,
	0x75, 0xf7, 0x94, 0xaa, 0x06, 0x2c, 0x65, 0x8d, 0x76, 0x60, 0xf7, 0x65, 0x7c, 0x21, 0x87, 0xa5,
	0x04, 0x8d, 0x86, 0x82, 0x25, 0xf7, 0x9f, 0xf0, 0x09, 0x59, 0xcc, 0x92, 0x99, 0xec, 0xcf, 0xe0,
	0xc0, 0x27, 0x96, 0x32, 0x43, 0xa1, 0x17, 0xb3, 0x64, 0x7e, 0x8c, 0x84, 0x6b, 0x8a, 0xb1, 0x29,
	0x2e, 0x63, 0x53, 0x3a, 0x18, 0xec, 0xb9, 0x0f, 0x6d, 0x11, 0xfa, 0x7f, 0x7d, 0xcf, 0xce, 0x1b,
	0xbe, 0xb6, 0x0f, 0xea, 0x04, 0x6a, 0x68, 0x5b, 0x20, 0x41, 0xf0, 0xa6, 0xaa, 0x06, 0xad, 0xae,
	0x9e, 0x56, 0x6a, 0x3a, 0xcc, 0x4e, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x06, 0xb0, 0x87, 0xfd,
	0xe0, 0x00, 0x00, 0x00,
}
