// Code generated by protoc-gen-go. DO NOT EDIT.
// source: stream_service.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StreamBlockContent struct {
	StreamID             string   `protobuf:"bytes,1,opt,name=streamID,proto3" json:"streamID,omitempty"`
	Index                uint64   `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	IsRoot               bool     `protobuf:"varint,4,opt,name=isRoot,proto3" json:"isRoot,omitempty"`
	Description          []byte   `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamBlockContent) Reset()         { *m = StreamBlockContent{} }
func (m *StreamBlockContent) String() string { return proto.CompactTextString(m) }
func (*StreamBlockContent) ProtoMessage()    {}
func (*StreamBlockContent) Descriptor() ([]byte, []int) {
	return fileDescriptor_296dc607c23b8aea, []int{0}
}

func (m *StreamBlockContent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamBlockContent.Unmarshal(m, b)
}
func (m *StreamBlockContent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamBlockContent.Marshal(b, m, deterministic)
}
func (m *StreamBlockContent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamBlockContent.Merge(m, src)
}
func (m *StreamBlockContent) XXX_Size() int {
	return xxx_messageInfo_StreamBlockContent.Size(m)
}
func (m *StreamBlockContent) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamBlockContent.DiscardUnknown(m)
}

var xxx_messageInfo_StreamBlockContent proto.InternalMessageInfo

func (m *StreamBlockContent) GetStreamID() string {
	if m != nil {
		return m.StreamID
	}
	return ""
}

func (m *StreamBlockContent) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *StreamBlockContent) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *StreamBlockContent) GetIsRoot() bool {
	if m != nil {
		return m.IsRoot
	}
	return false
}

func (m *StreamBlockContent) GetDescription() []byte {
	if m != nil {
		return m.Description
	}
	return nil
}

type StreamBlockContentList struct {
	Blocks               []*StreamBlockContent `protobuf:"bytes,1,rep,name=blocks,proto3" json:"blocks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *StreamBlockContentList) Reset()         { *m = StreamBlockContentList{} }
func (m *StreamBlockContentList) String() string { return proto.CompactTextString(m) }
func (*StreamBlockContentList) ProtoMessage()    {}
func (*StreamBlockContentList) Descriptor() ([]byte, []int) {
	return fileDescriptor_296dc607c23b8aea, []int{1}
}

func (m *StreamBlockContentList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamBlockContentList.Unmarshal(m, b)
}
func (m *StreamBlockContentList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamBlockContentList.Marshal(b, m, deterministic)
}
func (m *StreamBlockContentList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamBlockContentList.Merge(m, src)
}
func (m *StreamBlockContentList) XXX_Size() int {
	return xxx_messageInfo_StreamBlockContentList.Size(m)
}
func (m *StreamBlockContentList) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamBlockContentList.DiscardUnknown(m)
}

var xxx_messageInfo_StreamBlockContentList proto.InternalMessageInfo

func (m *StreamBlockContentList) GetBlocks() []*StreamBlockContent {
	if m != nil {
		return m.Blocks
	}
	return nil
}

type StreamRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StreamMap            uint64   `protobuf:"varint,2,opt,name=streamMap,proto3" json:"streamMap,omitempty"`
	StartIndex           uint64   `protobuf:"varint,3,opt,name=startIndex,proto3" json:"startIndex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamRequest) Reset()         { *m = StreamRequest{} }
func (m *StreamRequest) String() string { return proto.CompactTextString(m) }
func (*StreamRequest) ProtoMessage()    {}
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_296dc607c23b8aea, []int{2}
}

func (m *StreamRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamRequest.Unmarshal(m, b)
}
func (m *StreamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamRequest.Marshal(b, m, deterministic)
}
func (m *StreamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamRequest.Merge(m, src)
}
func (m *StreamRequest) XXX_Size() int {
	return xxx_messageInfo_StreamRequest.Size(m)
}
func (m *StreamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StreamRequest proto.InternalMessageInfo

func (m *StreamRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *StreamRequest) GetStreamMap() uint64 {
	if m != nil {
		return m.StreamMap
	}
	return 0
}

func (m *StreamRequest) GetStartIndex() uint64 {
	if m != nil {
		return m.StartIndex
	}
	return 0
}

type StreamRequestHandle struct {
	Value                uint64   `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamRequestHandle) Reset()         { *m = StreamRequestHandle{} }
func (m *StreamRequestHandle) String() string { return proto.CompactTextString(m) }
func (*StreamRequestHandle) ProtoMessage()    {}
func (*StreamRequestHandle) Descriptor() ([]byte, []int) {
	return fileDescriptor_296dc607c23b8aea, []int{3}
}

func (m *StreamRequestHandle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamRequestHandle.Unmarshal(m, b)
}
func (m *StreamRequestHandle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamRequestHandle.Marshal(b, m, deterministic)
}
func (m *StreamRequestHandle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamRequestHandle.Merge(m, src)
}
func (m *StreamRequestHandle) XXX_Size() int {
	return xxx_messageInfo_StreamRequestHandle.Size(m)
}
func (m *StreamRequestHandle) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamRequestHandle.DiscardUnknown(m)
}

var xxx_messageInfo_StreamRequestHandle proto.InternalMessageInfo

func (m *StreamRequestHandle) GetValue() uint64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func init() {
	proto.RegisterType((*StreamBlockContent)(nil), "StreamBlockContent")
	proto.RegisterType((*StreamBlockContentList)(nil), "StreamBlockContentList")
	proto.RegisterType((*StreamRequest)(nil), "StreamRequest")
	proto.RegisterType((*StreamRequestHandle)(nil), "StreamRequestHandle")
}

func init() { proto.RegisterFile("stream_service.proto", fileDescriptor_296dc607c23b8aea) }

var fileDescriptor_296dc607c23b8aea = []byte{
	// 284 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0x4d, 0x4b, 0xc3, 0x30,
	0x18, 0xc7, 0x49, 0xd7, 0x8d, 0xed, 0x99, 0x7a, 0xc8, 0xc6, 0x28, 0x32, 0x24, 0xf4, 0x54, 0x18,
	0xf4, 0xa0, 0xdf, 0x60, 0x2a, 0x38, 0xd0, 0x4b, 0xbc, 0x09, 0x22, 0xe9, 0xf2, 0x1c, 0xa2, 0x35,
	0x89, 0xcd, 0xd3, 0xb1, 0x0f, 0xe2, 0x07, 0x96, 0xa5, 0x45, 0x27, 0xbb, 0xe5, 0xff, 0x92, 0x97,
	0x5f, 0x1e, 0x98, 0x07, 0x6a, 0x50, 0x7d, 0xbe, 0x05, 0x6c, 0x76, 0x66, 0x8b, 0xa5, 0x6f, 0x1c,
	0xb9, 0xfc, 0x9b, 0x01, 0x7f, 0x8e, 0xc1, 0xba, 0x76, 0xdb, 0x8f, 0x5b, 0x67, 0x09, 0x2d, 0xf1,
	0x4b, 0x18, 0x77, 0xf5, 0xcd, 0x5d, 0xc6, 0x04, 0x2b, 0x26, 0xf2, 0x57, 0xf3, 0x39, 0x0c, 0x8d,
	0xd5, 0xb8, 0xcf, 0x12, 0xc1, 0x8a, 0x54, 0x76, 0x82, 0x73, 0x48, 0xb5, 0x22, 0x95, 0x0d, 0x04,
	0x2b, 0xce, 0x64, 0x5c, 0xf3, 0x05, 0x8c, 0x4c, 0x90, 0xce, 0x51, 0x96, 0x0a, 0x56, 0x8c, 0x65,
	0xaf, 0xb8, 0x80, 0xa9, 0xc6, 0xb0, 0x6d, 0x8c, 0x27, 0xe3, 0x6c, 0x36, 0x8c, 0x5b, 0x8e, 0xad,
	0xfc, 0x1e, 0x16, 0xa7, 0xaf, 0x7a, 0x34, 0x81, 0xf8, 0x0a, 0x46, 0xd5, 0xc1, 0x0b, 0x19, 0x13,
	0x83, 0x62, 0x7a, 0x3d, 0x2b, 0x4f, 0x8b, 0xb2, 0xaf, 0xe4, 0xaf, 0x70, 0xde, 0xa5, 0x12, 0xbf,
	0x5a, 0x0c, 0xc4, 0x2f, 0x20, 0x31, 0xba, 0x27, 0x4a, 0x8c, 0xe6, 0x4b, 0x98, 0x74, 0x5c, 0x4f,
	0xca, 0xf7, 0x3c, 0x7f, 0x06, 0xbf, 0x02, 0x08, 0xa4, 0x1a, 0xda, 0x44, 0xdc, 0x41, 0x8c, 0x8f,
	0x9c, 0x7c, 0x05, 0xb3, 0x7f, 0xc7, 0x3f, 0x28, 0xab, 0x6b, 0x3c, 0x7c, 0xd0, 0x4e, 0xd5, 0x2d,
	0xc6, 0x7b, 0x52, 0xd9, 0x89, 0xf5, 0x12, 0x16, 0xe1, 0x9d, 0xda, 0xd2, 0x79, 0xb4, 0x16, 0xa9,
	0x24, 0xdc, 0x93, 0xa9, 0xd1, 0x57, 0x2f, 0x89, 0xaf, 0xaa, 0x51, 0x1c, 0xc7, 0xcd, 0x4f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x9e, 0x7a, 0x2b, 0x59, 0xa6, 0x01, 0x00, 0x00,
}
