// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.11.4
// source: thread2.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/any"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Thread2Peer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Role int32  `protobuf:"varint,2,opt,name=role,proto3" json:"role,omitempty"`
}

func (x *Thread2Peer) Reset() {
	*x = Thread2Peer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_thread2_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Thread2Peer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Thread2Peer) ProtoMessage() {}

func (x *Thread2Peer) ProtoReflect() protoreflect.Message {
	mi := &file_thread2_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Thread2Peer.ProtoReflect.Descriptor instead.
func (*Thread2Peer) Descriptor() ([]byte, []int) {
	return file_thread2_proto_rawDescGZIP(), []int{0}
}

func (x *Thread2Peer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Thread2Peer) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

type Thread2Invite struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PeerId   string `protobuf:"bytes,1,opt,name=peerId,proto3" json:"peerId,omitempty"`
	ThreadId string `protobuf:"bytes,2,opt,name=threadId,proto3" json:"threadId,omitempty"`
	DbAddr   string `protobuf:"bytes,3,opt,name=dbAddr,proto3" json:"dbAddr,omitempty"`
	DbKey    string `protobuf:"bytes,4,opt,name=dbKey,proto3" json:"dbKey,omitempty"`
}

func (x *Thread2Invite) Reset() {
	*x = Thread2Invite{}
	if protoimpl.UnsafeEnabled {
		mi := &file_thread2_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Thread2Invite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Thread2Invite) ProtoMessage() {}

func (x *Thread2Invite) ProtoReflect() protoreflect.Message {
	mi := &file_thread2_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Thread2Invite.ProtoReflect.Descriptor instead.
func (*Thread2Invite) Descriptor() ([]byte, []int) {
	return file_thread2_proto_rawDescGZIP(), []int{1}
}

func (x *Thread2Invite) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *Thread2Invite) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *Thread2Invite) GetDbAddr() string {
	if x != nil {
		return x.DbAddr
	}
	return ""
}

func (x *Thread2Invite) GetDbKey() string {
	if x != nil {
		return x.DbKey
	}
	return ""
}

type Thread2MessageUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ThreadId   string `protobuf:"bytes,1,opt,name=threadId,proto3" json:"threadId,omitempty"`
	Collection string `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	InstanceId string `protobuf:"bytes,3,opt,name=instanceId,proto3" json:"instanceId,omitempty"`
	Instance   []byte `protobuf:"bytes,4,opt,name=instance,proto3" json:"instance,omitempty"`
}

func (x *Thread2MessageUpdate) Reset() {
	*x = Thread2MessageUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_thread2_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Thread2MessageUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Thread2MessageUpdate) ProtoMessage() {}

func (x *Thread2MessageUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_thread2_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Thread2MessageUpdate.ProtoReflect.Descriptor instead.
func (*Thread2MessageUpdate) Descriptor() ([]byte, []int) {
	return file_thread2_proto_rawDescGZIP(), []int{2}
}

func (x *Thread2MessageUpdate) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *Thread2MessageUpdate) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *Thread2MessageUpdate) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *Thread2MessageUpdate) GetInstance() []byte {
	if x != nil {
		return x.Instance
	}
	return nil
}

var File_thread2_proto protoreflect.FileDescriptor

var file_thread2_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x74, 0x68, 0x72, 0x65, 0x61, 0x64, 0x32, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x31, 0x0a, 0x0b, 0x54, 0x68,
	0x72, 0x65, 0x61, 0x64, 0x32, 0x50, 0x65, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6c,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x22, 0x71, 0x0a,
	0x0d, 0x54, 0x68, 0x72, 0x65, 0x61, 0x64, 0x32, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x70, 0x65, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x70, 0x65, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x68, 0x72, 0x65, 0x61, 0x64,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x68, 0x72, 0x65, 0x61, 0x64,
	0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x62, 0x41, 0x64, 0x64, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x64, 0x62, 0x41, 0x64, 0x64, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x64, 0x62,
	0x4b, 0x65, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x64, 0x62, 0x4b, 0x65, 0x79,
	0x22, 0x8e, 0x01, 0x0a, 0x14, 0x54, 0x68, 0x72, 0x65, 0x61, 0x64, 0x32, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x68, 0x72,
	0x65, 0x61, 0x64, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x68, 0x72,
	0x65, 0x61, 0x64, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6f, 0x6c, 0x6c, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63,
	0x65, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x69, 0x6e, 0x73, 0x74, 0x61,
	0x6e, 0x63, 0x65, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63,
	0x65, 0x42, 0x1c, 0x0a, 0x16, 0x73, 0x6a, 0x74, 0x75, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x6e, 0x65,
	0x74, 0x2e, 0x74, 0x65, 0x78, 0x74, 0x69, 0x6c, 0x65, 0x70, 0x62, 0x5a, 0x02, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_thread2_proto_rawDescOnce sync.Once
	file_thread2_proto_rawDescData = file_thread2_proto_rawDesc
)

func file_thread2_proto_rawDescGZIP() []byte {
	file_thread2_proto_rawDescOnce.Do(func() {
		file_thread2_proto_rawDescData = protoimpl.X.CompressGZIP(file_thread2_proto_rawDescData)
	})
	return file_thread2_proto_rawDescData
}

var file_thread2_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_thread2_proto_goTypes = []interface{}{
	(*Thread2Peer)(nil),          // 0: Thread2Peer
	(*Thread2Invite)(nil),        // 1: Thread2Invite
	(*Thread2MessageUpdate)(nil), // 2: Thread2MessageUpdate
}
var file_thread2_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_thread2_proto_init() }
func file_thread2_proto_init() {
	if File_thread2_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_thread2_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Thread2Peer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_thread2_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Thread2Invite); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_thread2_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Thread2MessageUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_thread2_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_thread2_proto_goTypes,
		DependencyIndexes: file_thread2_proto_depIdxs,
		MessageInfos:      file_thread2_proto_msgTypes,
	}.Build()
	File_thread2_proto = out.File
	file_thread2_proto_rawDesc = nil
	file_thread2_proto_goTypes = nil
	file_thread2_proto_depIdxs = nil
}
