// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.11.4
// source: thread2.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Thread2Invite struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PeerId   string `protobuf:"bytes,1,opt,name=peerId,proto3" json:"peerId,omitempty"`
	ThreadId string `protobuf:"bytes,2,opt,name=threadId,proto3" json:"threadId,omitempty"`
}

func (x *Thread2Invite) Reset() {
	*x = Thread2Invite{}
	if protoimpl.UnsafeEnabled {
		mi := &file_thread2_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Thread2Invite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Thread2Invite) ProtoMessage() {}

func (x *Thread2Invite) ProtoReflect() protoreflect.Message {
	mi := &file_thread2_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Thread2Invite.ProtoReflect.Descriptor instead.
func (*Thread2Invite) Descriptor() ([]byte, []int) {
	return file_thread2_proto_rawDescGZIP(), []int{0}
}

func (x *Thread2Invite) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *Thread2Invite) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

var File_thread2_proto protoreflect.FileDescriptor

var file_thread2_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x74, 0x68, 0x72, 0x65, 0x61, 0x64, 0x32, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x43, 0x0a, 0x0d, 0x54, 0x68, 0x72, 0x65, 0x61, 0x64, 0x32, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x70, 0x65, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x70, 0x65, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x68, 0x72, 0x65,
	0x61, 0x64, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x68, 0x72, 0x65,
	0x61, 0x64, 0x49, 0x64, 0x42, 0x1c, 0x0a, 0x16, 0x73, 0x6a, 0x74, 0x75, 0x2e, 0x6f, 0x70, 0x65,
	0x6e, 0x6e, 0x65, 0x74, 0x2e, 0x74, 0x65, 0x78, 0x74, 0x69, 0x6c, 0x65, 0x70, 0x62, 0x5a, 0x02,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_thread2_proto_rawDescOnce sync.Once
	file_thread2_proto_rawDescData = file_thread2_proto_rawDesc
)

func file_thread2_proto_rawDescGZIP() []byte {
	file_thread2_proto_rawDescOnce.Do(func() {
		file_thread2_proto_rawDescData = protoimpl.X.CompressGZIP(file_thread2_proto_rawDescData)
	})
	return file_thread2_proto_rawDescData
}

var file_thread2_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_thread2_proto_goTypes = []interface{}{
	(*Thread2Invite)(nil), // 0: Thread2Invite
}
var file_thread2_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_thread2_proto_init() }
func file_thread2_proto_init() {
	if File_thread2_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_thread2_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Thread2Invite); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_thread2_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_thread2_proto_goTypes,
		DependencyIndexes: file_thread2_proto_depIdxs,
		MessageInfos:      file_thread2_proto_msgTypes,
	}.Build()
	File_thread2_proto = out.File
	file_thread2_proto_rawDesc = nil
	file_thread2_proto_goTypes = nil
	file_thread2_proto_depIdxs = nil
}
